"""Generate an AA umbrella campaign that stretches the CG CAP bonds.

WHY THIS EXISTS
---------------
The bb6 wide160 models dissociate at dt=4fs and are stable at dt=1fs. The failure is
localised: 17 of 19 dissociation events start at the terminal cap bond C-N_nme. The cause
is a SUPPORT gap, not a stiffness defect -- measured 2026-08-06:

    training-set max cap bond    1.451 A
    MD at dt=1fs reaches         1.675 A   (whole molecule; caps stay well under)  -> stable
    MD at dt=4fs reaches         2.678 A                                            -> gone

Beyond 1.451 A the model has no data, so the force there is extrapolation. A dt=4fs
excursion crosses that edge, meets no restoring force, and runs away irreversibly.

The one wide160 that survives dt=4fs is the 5-bead model, whose training set reaches
1.772 A -- 0.097 A past its own AA reference -- because the alpha=1 teacher-bias campaign
incidentally stretched bonds. That augmentation was an ACCIDENT (it was logged as a defect:
a Cartesian bias on selected atoms stretches bonds instead of driving the target CV). This
script does deliberately, and controllably, what that campaign did by mistake.

WHAT IT DOES NOT SETTLE
-----------------------
Support and cap-topology are confounded in the 5-bead evidence: that lineage has BOTH an
extended support AND no cap beads. This campaign is the discriminator. Augment bb6, change
nothing else, re-run at dt=4fs:
    stable         -> support was the cause; a general recipe for CG timestep headroom
    still breaks   -> it is the cap topology, and augmentation is not the fix

DESIGN
------
* PLUMED RESTRAINT on the two cap bonds AS AA ATOM PAIRS. The mapping is atom-selection
  (bead == a specific AA atom), so the CG bond IS the AA distance: C_ace-N = atoms 5,7 and
  C-N_nme = atoms 15,17. No back-mapping is involved.
* ONE bond restrained per case, not both. Restraining both at once only produces jointly
  stretched geometries; alternating covers each coordinate independently, which is the
  shape the failure actually takes (one cap leaves, not both).
* Labels come from the BIAS-FREE rerun, exactly as in every other campaign. The unbiased
  AA force at a stretched bond IS the physical restoring force -- that is the entire
  content we are trying to teach.
* dt=1fs, not the reference's 2fs. A ~240,000 kJ/mol/nm^2 restraint adds a stiff mode, and
  2 fs is already marginal for an unconstrained heavy-atom bond.
* No CG bias server: this is pure PLUMED, so `sampling/cases.py` (which always launches the
  socket server) is deliberately not reused. The case LAYOUT is kept identical --
  biased.trr + unbiased_forces.trr + campaign.json -- so `sampling/collect.py` works
  unchanged and applies the same persisted aggforce matrix.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from .mapping import get_mapping

REPO = Path(__file__).resolve().parents[1]

RUN_CASE = """#!/bin/bash
# Generated by sampling/build_bond_stretch_campaign.py -- do not edit by hand.
set -Eeuo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
cd "$HERE"

module --force purge
module load Stages/2025
module load GCC/13.3.0 ParaStationMPI/5.11.0-1
module load GROMACS/2024.3-PLUMED-2.9.3

gmx grompp -f production.mdp -c {structure} -p {topology} -o biased.tpr -maxwarn 2
gmx mdrun -deffnm biased -plumed plumed.dat -ntmpi 1 -ntomp {ntomp}

# Bias-free force rerun -- MANDATORY. Training labels must be the unbiased AA forces;
# the restraint force must never reach the dataset.
gmx mdrun -s biased.tpr -rerun biased.trr -deffnm unbiased_forces -ntmpi 1 -ntomp {ntomp}

echo "case {case} complete"
"""

PLUMED = """# Cap-bond stretch umbrella. Distances are AA atom pairs because the CG mapping is
# atom-selection: bead {bead_a} IS atom {atom_a}, bead {bead_b} IS atom {atom_b}.
d_ace: DISTANCE ATOMS=5,7
d_nme: DISTANCE ATOMS=15,17
RESTRAINT ARG={target_cv} AT={target_nm:.4f} KAPPA={kappa:.0f} LABEL=umb
PRINT ARG=d_ace,d_nme,umb.bias FILE=colvar.dat STRIDE={print_stride}
"""


def build(out_dir: Path, structure: str, topology: str, mdp_template: Path,
          windows_A, n_per_window: int, ps_per_case: float, kappa: float,
          ntomp: int, mapping_name: str) -> None:
    m = get_mapping(mapping_name)
    caps = [(0, 1, "d_ace"), (4, 5, "d_nme")]
    base_mdp = mdp_template.read_text()

    dt_fs = 1.0
    nsteps = int(ps_per_case * 1000 / dt_fs)
    # 0.1 ps spacing, matching every other campaign's collection cadence
    nst_out = int(100 / dt_fs)

    mdp = []
    for line in base_mdp.splitlines():
        s = line.strip()
        if s.startswith("nsteps"):
            line = f"nsteps                  = {nsteps} ; {ps_per_case} ps at {dt_fs} fs"
        elif s.startswith("dt "):
            line = f"dt                      = {dt_fs/1000:.4f}    ; {dt_fs} fs"
        elif s.startswith("nstxout ") or s.startswith("nstfout"):
            key = s.split()[0]
            line = f"{key:<24}= {nst_out}          ; every 0.1 ps"
        elif s.startswith("gen_vel") or s.startswith("continuation"):
            continue
        mdp.append(line)
    mdp_body = "\n".join(mdp)

    out_dir.mkdir(parents=True, exist_ok=True)
    cases = []
    idx = 0
    for bi, bj, cv in caps:
        for target_A in windows_A:
            for rep in range(n_per_window):
                name = f"case_{idx:02d}_{cv}_{target_A:.2f}A_r{rep}"
                d = out_dir / name
                d.mkdir(parents=True, exist_ok=True)
                # per-case velocity seed: without this every replica of a window is the
                # same trajectory, the bug that made the first bb6 pilot useless
                seed = 20260806 + idx
                (d / "production.mdp").write_text(
                    mdp_body
                    + f"\ngen_vel                 = yes\ngen_temp                = 298\n"
                      f"gen_seed                = {seed}\ncontinuation            = no\n"
                )
                (d / "plumed.dat").write_text(PLUMED.format(
                    bead_a=m.bead_labels[bi], atom_a=m.aa_atom_indices_1based[bi],
                    bead_b=m.bead_labels[bj], atom_b=m.aa_atom_indices_1based[bj],
                    target_cv=cv, target_nm=target_A / 10.0, kappa=kappa, print_stride=100))
                rc = d / "run_case.sh"
                rc.write_text(RUN_CASE.format(structure=structure, topology=topology,
                                              ntomp=ntomp, case=name))
                rc.chmod(0o755)
                cases.append({"case": name, "cv": cv, "target_A": target_A,
                              "bond": f"{m.bead_labels[bi]}-{m.bead_labels[bj]}",
                              "atoms": [m.aa_atom_indices_1based[bi], m.aa_atom_indices_1based[bj]],
                              "seed": seed})
                idx += 1

    (out_dir / "campaign.json").write_text(json.dumps({
        "name": out_dir.name, "mapping": mapping_name, "n_cases": len(cases),
        "purpose": "extend CG cap-bond support beyond the reference max of 1.451 A",
        "windows_A": list(windows_A), "kappa_kJ_mol_nm2": kappa,
        "dt_fs": dt_fs, "ps_per_case": ps_per_case,
        "required_discard_ps": 20.0,
        "labels": "unbiased_forces.trr (bias-free rerun); restraint force excluded",
        "cases": cases,
    }, indent=2))

    slurm = out_dir / "submit.slurm"
    slurm.write_text(f"""#!/bin/bash
#SBATCH --job-name=bb6_capstretch
#SBATCH --account=cameo
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=16
#SBATCH --time=01:00:00
#SBATCH --partition=booster
#SBATCH --gres=gpu:1
#SBATCH --array=0-{len(cases)-1}
#SBATCH --output={out_dir}/%A_%a.out
#SBATCH --error={out_dir}/%A_%a.err
set -Eeuo pipefail
CASES=({' '.join(c['case'] for c in cases)})
cd "{out_dir}/${{CASES[$SLURM_ARRAY_TASK_ID]}}"
srun --ntasks-per-node=1 ./run_case.sh
""")
    print(f"wrote {len(cases)} cases to {out_dir}")
    print(f"  windows: {list(windows_A)} A on each of 2 cap bonds x {n_per_window} replicas")
    print(f"  {ps_per_case} ps/case at dt={dt_fs}fs, 0.1 ps output -> "
          f"~{int(ps_per_case/0.1)} frames/case, ~{int(len(cases)*ps_per_case/0.1)} total")
    print(f"  submit: sbatch {slurm}")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--structure", required=True)
    ap.add_argument("--topology", required=True)
    ap.add_argument("--mdp", type=Path,
                    default=REPO / "sampling/campaigns/production_298K_dt1fs.mdp")
    ap.add_argument("--windows", type=float, nargs="+", default=[1.45, 1.55, 1.65, 1.75],
                    help="cap-bond restraint targets in Angstrom; reference max is 1.451")
    ap.add_argument("--n-per-window", type=int, default=3)
    ap.add_argument("--ps-per-case", type=float, default=200.0)
    ap.add_argument("--kappa", type=float, default=300000.0,
                    help="kJ/mol/nm^2; must exceed the amide bond constant (~238,000) to hold")
    ap.add_argument("--ntomp", type=int, default=8)
    ap.add_argument("--mapping", default="ala2_backbone_cb_6")
    a = ap.parse_args()
    build(a.out, a.structure, a.topology, a.mdp, a.windows, a.n_per_window,
          a.ps_per_case, a.kappa, a.ntomp, a.mapping)


if __name__ == "__main__":
    main()
