#!/usr/bin/env python3
"""Stage 3: restrained AA simulations at fixed CG coordinates, for CONDITIONAL MEAN FORCES.

    python -m sampling.build_meanforce_campaign \
        --frames-npz <harvest>/cg_coords_all.npz --source-campaign <harvest> \
        --topology topol.top --mdp production.mdp --outdir local_work/meanforce \
        --n-states 512 --ps-per-state 314

WHY
    A single AA frame gives a force label with sigma_F ~ 19.8 kcal/mol/A against a true mean
    force of 0.5-2.8 -- a 1:10 signal-to-noise ratio. Averaging N decorrelated realisations at
    FIXED CG coordinates cuts that as 1/sqrt(N):

        SE = 1.0 kcal/mol/A  ->    392 frames ->   78 ps/state
        SE = 0.5             ->  1,568        ->  314 ps/state
        SE = 0.2             ->  9,801        -> 1960 ps/state

    At 14,936 ns/day/node (64 replicas, MPS) even 1000 states at SE=0.2 is ~3 node-hours, so
    COMPUTE IS NOT THE CONSTRAINT for ala2 -- storage and physics correctness are.

TWO CHOICES THAT ARE NOT INTERCHANGEABLE
  * **Selection uses INTERNAL coordinates** (the 15 bead-pair distances, the same features the
    TICA projection uses). The molecule rotates freely under WHOLEMOLECULES, so farthest-point
    selection on raw Cartesian coordinates would happily return rotated copies of one
    conformation and call them distinct states.
  * **Restraint uses ABSOLUTE bead positions** of the selected frame. This pins the molecule in
    the box, fixing all 18 bead DOF including the 6 global ones. That is the deliberate choice
    for this first run.

PLUMED RESTRAINT, NOT GROMACS posres
    The bias-free rerun is `gmx mdrun -rerun` WITHOUT `-plumed`. A topology-level `posres`
    would still be applied during that rerun and would silently contaminate the forces the
    whole stage exists to measure. A PLUMED restraint vanishes cleanly.
    (Also: PLUMED RESTRAINT is `0.5*KAPPA*d^2` -- the 1/2 IS included, unlike UPPER_WALLS which
    has none. Verified empirically against the deployed kernel.)
"""
from __future__ import annotations

import argparse
import concurrent.futures as cf
import json
import subprocess
import time
from pathlib import Path

import mdtraj as md
import numpy as np

GMX_MODULES = "Stages/2025 GCC/13.3.0 ParaStationMPI/5.11.0-1 GROMACS/2024.3-PLUMED-2.9.3"

PLUMED_TEMPLATE = """\
# Generated by sampling/build_meanforce_campaign.py -- do not edit by hand.
# state {state}: CG coordinates restrained to the seed frame; mean force measured from the
# BIAS-FREE rerun, so this restraint must live in PLUMED and NOT in the topology.
UNITS LENGTH=A ENERGY=kcal/mol
WHOLEMOLECULES ENTITY0={atoms}

{positions}
# 0.5*KAPPA*d^2 per component; thermal width sqrt(kT/KAPPA) = {width:.3f} A
rest: RESTRAINT ARG={args} AT={at} KAPPA={kappa}

PRINT ARG={args},rest.bias FILE=colvar.dat STRIDE={stride}
"""


def _seeds_for_replica(job):
    """Convert ONE source replica once, then write every seed drawn from it.

    Module-level and self-contained so it can run in a ProcessPoolExecutor: the two I/O
    phases (trjconv PBC conversion, .gro writing) are ~30 min serially for 256 replicas and
    42,000 seeds, and both are embarrassingly parallel across replicas.
    """
    import subprocess
    import mdtraj as md
    import numpy as np
    ri, items, rep_dir, outdir, tmpdir, gmx, bead_atoms0 = job
    rep_dir, outdir, tmpdir = Path(rep_dir), Path(outdir), Path(tmpdir)
    src = next((rep_dir / n for n in ("biased.trr", "biased.xtc")
                if (rep_dir / n).exists()), None)
    if src is None:
        return ri, {}, f"{rep_dir}: neither biased.trr nor biased.xtc present"
    whole = tmpdir / f"whole_{ri:05d}.trr"
    cmd = (f"module --force purge >/dev/null 2>&1; "
           f"module load {GMX_MODULES} >/dev/null 2>&1; "
           f"{gmx} trjconv -f {src} -s {rep_dir/'biased.tpr'} "
           f"-o {whole} -pbc mol -center")
    proc = subprocess.run(["bash", "-lc", cmd], input="Protein\nSystem\n",
                          text=True, capture_output=True)
    if proc.returncode != 0 or not whole.exists():
        return ri, {}, f"{rep_dir.name}: trjconv rc={proc.returncode}\n{proc.stderr[-600:]}"
    try:
        traj = md.load(str(whole), top=str(rep_dir / "biased.gro"))
        out = {}
        for k, t_ps in items:
            j = int(np.argmin(np.abs(traj.time - t_ps)))
            if abs(float(traj.time[j]) - t_ps) > 1e-3:
                return ri, out, (f"state_{k:05d}: no frame at t={t_ps} ps "
                                 f"(nearest {float(traj.time[j])})")
            d = outdir / f"state_{k:05d}"
            d.mkdir(parents=True, exist_ok=True)
            fr = traj[j]
            fr.save_gro(str(d / "seed.gro"))
            # Return what the caller would otherwise RE-READ from the file we just wrote.
            # That re-read cost ~40 ms/state -- 35 min at 42,000 states, and it was the
            # dominant phase of the build once seed extraction had been parallelised.
            # ROUND TO .gro PRECISION (3 decimals in nm = 0.01 A). The simulation freezes
            # the beads at whatever seed.gro says, and this value becomes `R` in the final
            # dataset, so it must be what GROMACS will actually read -- not the higher-
            # precision in-memory coordinate. Skipping this made the recorded R disagree
            # with the frozen configuration by up to 5e-03 A on every state.
            out[k] = (np.asarray(np.round(fr.xyz[0][bead_atoms0], 3) * 10.0, np.float64),
                      np.asarray(fr.unitcell_vectors[0] * 10.0, np.float64))
    finally:
        whole.unlink(missing_ok=True)
    return ri, out, None


def pbc_margin(x: np.ndarray, H: np.ndarray) -> float:
    """Shortest perpendicular distance from any point in `x` to a face of the cell `H`.

    `H` has the box vectors as ROWS (mdtraj's `unitcell_vectors`). The production boxes are
    rhombic dodecahedra, where a min/max test on Cartesian components is meaningless -- the
    cell is not an axis-aligned brick. Work in fractional coordinates `s = x H^-1` instead:
    the interplanar spacing perpendicular to the face spanned by the other two vectors is
    `1/|g_i|`, with `g_i` the i-th COLUMN of `H^-1`, so the distance to that face pair is
    `min(s_i, 1-s_i)/|g_i|`.
    """
    Hinv = np.linalg.inv(H)
    s = x @ Hinv                                        # fractional coordinates
    spacing = 1.0 / np.linalg.norm(Hinv, axis=0)        # perpendicular width per direction
    return float(np.min(np.minimum(s, 1.0 - s) * spacing))


def farthest_point_gpu(X: np.ndarray, n: int, start: int):
    """Farthest-point selection on the GPU. Returns (indices, separation-at-each-step).

    The greedy loop is n iterations of a full (n_pool x d) distance evaluation -- for
    512,256 frames and 42,000 states that is ~3e11 flops: 11 min in numpy, seconds on a GH200.

    **float64, deliberately.** In float32 the selection is NOT reproducible against the numpy
    path: near-ties in the argmax resolve differently, one pick diverges and everything after
    it compounds. Measured at n=3000 the float32 run chose the SAME SET (3000/3000 overlap)
    and the same final separation, so it is not wrong -- but float64 reproduces the numpy
    sequence exactly and still runs 34x faster, which is worth the ~3x over float32.
    """
    import jax, jax.numpy as jnp
    from jax import lax
    jax.config.update("jax_enable_x64", True)
    Xj = jnp.asarray(X, jnp.float64)
    d0 = jnp.linalg.norm(Xj - Xj[start], axis=1)

    def step(d, _):
        j = jnp.argmax(d)
        return jnp.minimum(d, jnp.linalg.norm(Xj - Xj[j], axis=1)), (j, d[j])

    _, (js, seps) = lax.scan(step, d0, None, length=n - 1)
    idx = np.concatenate([[start], np.asarray(js)])
    sep = np.concatenate([[np.inf], np.asarray(seps)])
    return idx, sep


def farthest_point(X: np.ndarray, n: int, min_sep: float, rng) -> np.ndarray:
    """Greedy farthest-point selection with a minimum-separation floor.

    Returns indices. Stops early (with a warning) if `min_sep` cannot be met -- silently
    returning near-duplicates would make `n_states` a lie and concentrate the whole stage in
    one basin.
    """
    idx = [int(rng.integers(len(X)))]
    d = np.linalg.norm(X - X[idx[0]], axis=1)
    while len(idx) < n:
        j = int(np.argmax(d))
        if d[j] < min_sep:
            print(f"  !! stopped at {len(idx)}/{n} states: farthest remaining point is "
                  f"{d[j]:.3f} < --min-separation {min_sep}")
            break
        idx.append(j)
        d = np.minimum(d, np.linalg.norm(X - X[j], axis=1))
    return np.asarray(idx)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--source-campaign", type=Path, required=True,
                    help="campaign with replica_*/{cg_coords.npz,biased.trr|biased.xtc}; run "
                         "`collect.py --coords-only` on it first")
    ap.add_argument("--topology", required=True)
    ap.add_argument("--mdp", type=Path, required=True)
    ap.add_argument("--outdir", type=Path, required=True)
    ap.add_argument("--mapping", default="ala2_backbone_cb_6")
    ap.add_argument("--n-states", type=int, default=512)
    ap.add_argument("--min-separation", type=float, default=0.15,
                    help="minimum L2 distance in pair-distance space (Angstrom) between states")
    ap.add_argument("--ps-per-state", type=float, default=314.0)
    ap.add_argument("--output-ps", type=float, default=0.2,
                    help="force/coord output interval; the decorrelation time inside a basin "
                         "is ~0.2 ps, so sampling faster buys correlated frames and disk")
    ap.add_argument("--restraint-width", type=float, default=0.1,
                    help="thermal width in Angstrom; KAPPA = kT/width^2")
    ap.add_argument("--kappa", type=float, default=None, help="override KAPPA directly")
    ap.add_argument("--freeze", action="store_true",
                    help="hold the CG beads EXACTLY fixed with GROMACS `freezegrps` instead of "
                         "a PLUMED harmonic restraint. This is the correct conditional "
                         "ensemble: a finite restraint averages the force over a window of "
                         "width sqrt(kT/kappa), which for a PMF of curvature H scales every "
                         "measured force by kappa/(kappa+H). Measured 2026-08-15: kappa=59.2 "
                         "captured only 24%% of the true mean force (H ~ 192, p90 896).")
    ap.add_argument("--kbt", type=float, default=0.5921868690749673)
    ap.add_argument("--source-discard-ps", type=float, default=20.0,
                    help="drop this much from the START of each source replica before "
                         "selecting; `collect.py --coords-only` does NOT discard (its "
                         "--discard-ps only applies on the force path), so the frames run "
                         "from t=0 and the equilibration must be excluded here")
    ap.add_argument("--conformation-tol", type=float, default=0.05,
                    help="max |d(pair distance)| in Angstrom between the selected frame and "
                         "the extracted seed.gro before the build aborts")
    ap.add_argument("--pbc-margin", type=float, default=6.0,
                    help="minimum Angstrom between any restrained bead and a box face; an "
                         "absolute-position restraint cannot survive a re-wrap")
    ap.add_argument("--replicas-per-job", type=int, default=32)
    ap.add_argument("--gpus-per-node", type=int, default=4)
    ap.add_argument("--wall-hours", type=float, default=2.0)
    ap.add_argument("--seed-jobs", type=int, default=32,
                    help="parallel workers for seed extraction. Both I/O phases (trjconv PBC "
                         "conversion and .gro writing) are per-replica independent; serially "
                         "they are ~30 min for 256 replicas and 42,000 seeds.")
    ap.add_argument("--gpu-select", action="store_true",
                    help="run farthest-point selection on the GPU. Bit-identical to the numpy "
                         "path; 1.8 s vs 11 min for 42,000 states from a 512k pool.")
    ap.add_argument("--groups-per-task", type=int, default=1,
                    help="GROUPS run back-to-back inside one SLURM array task. Startup is "
                         "~0.70 s/replica and does not amortise, so a many-state campaign is "
                         "startup-bound; bundling at least keeps the SLURM prolog from adding "
                         "to it.")
    ap.add_argument("--gmx", default="gmx")
    ap.add_argument("--seed", type=int, default=20260813)
    a = ap.parse_args()

    from sampling.launch import cpus_per_rank, group_ranges, multidir_group_script, submit_script
    from sampling.mapping import get_mapping

    m = get_mapping(a.mapping)
    atoms = m.aa_atom_indices_1based
    kappa = a.kappa if a.kappa is not None else a.kbt / a.restraint_width ** 2
    width = np.sqrt(a.kbt / kappa)

    # Read the PER-CASE files, which carry exact `time_ps`. Reconstructing the time from a
    # concatenated array and an assumed discard/stride is how the first version picked frames
    # 20 ps away from the ones it had selected -- the conformations differed by up to 1.99 A
    # in pair distance and the restraint then had ~500 kcal/mol of energy at step 0.
    reps = sorted(p for p in a.source_campaign.glob("replica_*") if p.is_dir()) or \
        sorted(p for p in a.source_campaign.glob("case_*") if p.is_dir())
    if not reps:
        raise SystemExit(f"no replica_*/case_* under {a.source_campaign}")
    Rs, prov = [], []
    for ri, rp in enumerate(reps):
        f = rp / "cg_coords.npz"
        if not f.exists():
            raise SystemExit(f"{f} missing -- run `collect.py --coords-only` on the campaign")
        z = np.load(f)
        t = z["time_ps"].astype(np.float64)
        keep = t >= (t[0] + a.source_discard_ps)
        # If the .trr is gone and we will extract seeds from the .xtc, restrict selection to
        # times the XTC ACTUALLY HAS. `cg_coords.npz` comes from the .trr (nstxout, 0.1 ps)
        # while the .xtc is written at nstxout-compressed (1.0 ps here), so `trjconv -dump`
        # would silently return the nearest stored frame -- up to 0.5 ps away, which is ~2 tau
        # and a genuinely different conformation (measured: 0.274 A of pair-distance drift).
        if not (rp / "biased.trr").exists() and (rp / "biased.xtc").exists():
            import mdtraj as _md
            with _md.open(str(rp / "biased.xtc")) as fh:
                xtc_t = np.asarray(fh.read()[1], dtype=np.float64)
            keep &= np.isclose(t[:, None], xtc_t[None, :], atol=1e-3).any(axis=1)
        Rs.append(z["R"].astype(np.float64)[keep])
        prov += [(ri, float(tt)) for tt in t[keep]]
    R = np.concatenate(Rs)
    print(f"{len(reps)} source replicas, {len(R)} frames after dropping "
          f"{a.source_discard_ps} ps each")

    # SELECTION METRIC: internal pair distances, not Cartesian -- see the module docstring
    iu = np.triu_indices(R.shape[1], k=1)
    D = np.linalg.norm(R[:, iu[0], :] - R[:, iu[1], :], axis=-1)
    rng = np.random.default_rng(a.seed)
    if a.gpu_select:
        start = int(rng.integers(len(D)))
        pick, sep = farthest_point_gpu(D, a.n_states, start)
        below = int((sep[1:] < a.min_separation).sum())
        if below:
            keep = int(np.argmax(sep[1:] < a.min_separation)) + 1
            print(f"  !! separation fell below --min-separation {a.min_separation} at state "
                  f"{keep}; truncating {a.n_states} -> {keep}")
            pick, sep = pick[:keep], sep[:keep]
        print(f"  GPU selection: separation at the last state {sep[-1]:.4f} A "
              f"(median over states {np.median(sep[1:]):.4f})")
    else:
        pick = farthest_point(D, a.n_states, a.min_separation, rng)
    nn = [np.min(np.linalg.norm(D[pick] - D[p], axis=1)[np.arange(len(pick)) != i])
          for i, p in enumerate(pick)]
    print(f"{len(R)} frames -> {len(pick)} states; nearest-neighbour separation "
          f"min {np.min(nn):.3f} median {np.median(nn):.3f} A (pair-distance space)")

    a.outdir.mkdir(parents=True, exist_ok=True)
    nsteps = int(a.ps_per_state * 1000)                # dt = 1 fs
    nst_out = int(a.output_ps * 1000)
    base = a.mdp.read_text().splitlines()
    manifest = {"n_states": int(len(pick)), "kappa_kcal_mol_A2": float(kappa),
                "restraint_width_A": float(width), "ps_per_state": a.ps_per_state,
                "output_ps": a.output_ps,
                "expected_frames_per_state": int(a.ps_per_state / a.output_ps),
                "expected_SE": float(19.8 / np.sqrt(a.ps_per_state / a.output_ps)),
                "selection": "farthest-point on 15 bead-pair distances",
                "restraint": "absolute bead positions (PLUMED POSITION+RESTRAINT)",
                "states": []}
    print(f"  KAPPA {kappa:.1f} kcal/mol/A^2 (width {width:.3f} A); "
          f"{a.ps_per_state} ps/state -> {manifest['expected_frames_per_state']} frames, "
          f"expected SE ~ {manifest['expected_SE']:.2f} kcal/mol/A")

    # ---- SEED PRE-PASS ---------------------------------------------------------------
    # One trjconv per SOURCE REPLICA, not per state. The per-state call (subprocess + module
    # load, ~1.2 s) is invisible at 512 states and fatal at 50,000: 16.7 h of login-node CPU
    # before a single GPU starts, several times the whole MD budget. States are grouped by
    # their source replica; each replica's trajectory is converted ONCE with the identical
    # `-pbc mol -center` semantics, then every seed drawn from it is written in Python.
    # Keeping trjconv for the PBC step matters -- the conformation and pbc-margin guards were
    # calibrated against its output, and they still run per state below.
    by_rep: dict[int, list[tuple[int, float]]] = {}
    for k, fi in enumerate(pick):
        ri, t_ps = prov[int(fi)]
        by_rep.setdefault(ri, []).append((k, t_ps))

    tmpdir = a.outdir / "_seedtmp"
    tmpdir.mkdir(parents=True, exist_ok=True)
    bead_atoms0 = [q - 1 for q in atoms]
    jobs = [(ri, items, str(reps[ri]), str(a.outdir), str(tmpdir), a.gmx, bead_atoms0)
            for ri, items in sorted(by_rep.items())]
    workers = max(1, min(a.seed_jobs, len(jobs)))
    seed_cache: dict[int, tuple] = {}
    t_seed = time.time()
    # spawn, not fork: JAX is already initialised (GPU selection ran above) and it is
    # multithreaded, so os.fork() risks a deadlock -- Python warns about exactly this.
    import multiprocessing as _mp
    with cf.ProcessPoolExecutor(max_workers=workers,
                                mp_context=_mp.get_context("spawn")) as ex:
        for ri, got, err in ex.map(_seeds_for_replica, jobs):
            if err:
                raise SystemExit(err)
            seed_cache.update(got)
    n_written = len(seed_cache)
    print(f"  seeds: {n_written} written from {len(by_rep)} source trajectories "
          f"in {time.time()-t_seed:.0f} s on {workers} workers")

    case_dirs, margins = [], []
    for k, fi in enumerate(pick):
        d = a.outdir / f"state_{k:05d}"
        d.mkdir(parents=True, exist_ok=True)
        ri, t_ps = prov[int(fi)]
        if not (d / "seed.gro").exists():
            raise SystemExit(f"{d.name}: seed.gro missing -- the seed pre-pass did not run")

        # TARGET COMES FROM THE EXTRACTED SEED, not from the collected array. trjconv applies
        # its own PBC treatment, so the two differ in absolute placement; restraining to the
        # array value put 164-570 kcal/mol into the restraint at step 0 and blew the run up.
        # Taking AT from seed.gro makes the initial restraint force exactly zero.
        seed, seed_box = seed_cache[k]      # returned by the worker; no re-read
        # ...but verify it is still the CONFORMATION that was selected. Placement may differ;
        # internal geometry must not.
        iu2 = np.triu_indices(len(atoms), k=1)
        dsel = np.linalg.norm(R[fi][iu2[0]] - R[fi][iu2[1]], axis=-1)
        dsee = np.linalg.norm(seed[iu2[0]] - seed[iu2[1]], axis=-1)
        dev = float(np.abs(dsel - dsee).max())
        if dev > a.conformation_tol:
            raise SystemExit(
                f"{d.name}: extracted seed is NOT the selected conformation "
                f"(max |d(pair distance)| = {dev:.3f} A > {a.conformation_tol}). "
                f"frame {fi} -> {reps[ri].name} t={t_ps} ps")
        # PBC margin: how close does any restrained bead sit to a box face? The production
        # boxes are rhombic dodecahedra (angles 60/60/90), so an axis-aligned min/max test is
        # meaningless -- do it in fractional coordinates against the true interplanar spacings.
        margin = pbc_margin(seed, seed_box)
        if margin < a.pbc_margin:
            raise SystemExit(f"{d.name}: bead within {margin:.1f} A of a box face "
                             f"(need {a.pbc_margin}); absolute-position restraint is unsafe")
        margins.append(margin)
        tgt = seed
        pos = "\n".join(f"p{b}: POSITION ATOM={atoms[b]} NOPBC" for b in range(len(atoms)))
        args = ",".join(f"p{b}.{c}" for b in range(len(atoms)) for c in "xyz")
        at = ",".join(f"{tgt[b, c]:.6f}" for b in range(len(atoms)) for c in range(3))
        if not a.freeze:
            (d / "plumed.dat").write_text(PLUMED_TEMPLATE.format(
                state=k, atoms=m.plumed_atom_selection(), positions=pos, args=args,
                at=at, kappa=",".join([f"{kappa:.6f}"] * (3 * len(atoms))), width=width,
                stride=nst_out))

        mdp = []
        for line in base:
            t = line.strip()
            if t.startswith("nsteps"):
                line = f"nsteps                  = {nsteps} ; {a.ps_per_state} ps"
            elif t.startswith(("nstxout", "nstfout")):
                line = f"{t.split()[0]:<24}= {nst_out}          ; {a.output_ps} ps"
            elif t.startswith(("gen_vel", "gen-vel")):
                line = "gen_vel                 = yes        ; seed.gro carries no velocities"
            elif t.startswith("gen_temp"):
                line = "gen_temp                = 298"
            elif t.startswith("gen_seed"):
                line = f"gen_seed                = {a.seed + k}"
            elif t.startswith("continuation"):
                line = "continuation            = no         ; fresh velocities need constraining"
            elif t.startswith(("pcoupltype", "pcoupl-type")):
                pass                         # harmless once pcoupl = no; leave it alone
            elif t.startswith("pcoupl"):
                # NVT. Two independent reasons, both fatal in the NPT dry run (job 1367550):
                #   1. an absolute-position restraint fights an isotropic barostat by
                #      construction -- the barostat rescales coordinates that RESTRAINT pins
                #      in fixed lab space, so the two never reach a consistent state;
                #   2. Parrinello-Rahman from gen_vel=yes is unstable, and gen_vel=yes is now
                #      mandatory (seed.gro carries no velocities). The box went NaN at 6 ps.
                # The seed comes from an equilibrated NPT trajectory, so the density is already
                # right, and the conditional mean force is a configurational average that the
                # barostat does not change.
                line = ("pcoupl                  = no        ; NVT: barostat conflicts with "
                        "the absolute-position restraint")
            elif t.startswith(("tcoupl", "tcoupl-type")):
                line = ("tcoupl                  = v-rescale ; stable from freshly generated "
                        "velocities, unlike nose-hoover")
            mdp.append(line)
        # the source mdp may not define these at all -- an NPT-continuation mdp has
        # gen_vel=no/continuation=yes, which starts the run at ~6 K and it dies
        have = {l.split("=")[0].strip().replace("-", "_").lower() for l in mdp if "=" in l}
        for key, val in (("gen_vel", "yes"), ("gen_temp", "298"),
                         ("gen_seed", str(a.seed + k)), ("continuation", "no"),
                         ("pcoupl", "no"), ("tcoupl", "v-rescale")):
            if key not in have:
                mdp.append(f"{key:<24}= {val}   ; added by build_meanforce_campaign")
        if a.freeze:
            # `freezegrps` zeroes the UPDATE of these atoms, not their forces: GROMACS still
            # computes and writes them, verified identical between the frozen run and the
            # bias-free rerun. comm-mode must be None -- removing centre-of-mass motion is
            # ill-defined once part of the system is nailed down.
            mdp = [l for l in mdp
                   if not l.strip().startswith(("freezegrps", "freezedim",
                                                "comm-mode", "comm_mode"))]
            mdp += ["freezegrps              = CGbeads   ; CG beads held EXACTLY fixed",
                    "freezedim               = Y Y Y",
                    "comm-mode               = None      ; ill-defined with frozen atoms"]
        (d / "production.mdp").write_text("\n".join(mdp) + "\n")

        case_dirs.append(d.name)
        manifest["states"].append(dict(state=k, frame=int(fi), replica=reps[ri].name,
                                       t_ps=float(t_ps),
                                       target=tgt.round(4).tolist(),
                                       selected=R[fi].round(4).tolist(),
                                       conformation_dev_A=dev,
                                       pbc_margin_A=margin))

    manifest["ensemble"] = "NVT (pcoupl=no, tcoupl=v-rescale)"
    manifest["min_pbc_margin_A"] = float(np.min(margins))
    if a.freeze:
        # One shared index at the campaign root. A custom `-n` file REPLACES the default
        # groups, so it must be generated by make_ndx (which emits System/Protein/... that the
        # mdp's tc-grps still reference) and only then extended with the bead group.
        ndx = a.outdir / "beads.ndx"
        sel = " ".join(str(i) for i in atoms)
        cmd = (f"module --force purge >/dev/null 2>&1; "
               f"module load {GMX_MODULES} >/dev/null 2>&1; "
               f"printf 'a {sel}\\nq\\n' | {a.gmx} make_ndx "
               f"-f {a.outdir/case_dirs[0]/'seed.gro'} -o {ndx}")
        proc = subprocess.run(["bash", "-lc", cmd], capture_output=True, text=True)
        if proc.returncode != 0 or not ndx.exists():
            raise SystemExit(f"make_ndx failed (rc={proc.returncode})\n{proc.stderr[-1200:]}")
        txt = ndx.read_text()
        i = txt.rfind("[")
        ndx.write_text(txt[:i] + "[ CGbeads ]" + txt[txt.index("]", i) + 1:])
        n_grp = txt.count("[")
        print(f"  wrote {ndx.name}: {n_grp} groups, last renamed to [ CGbeads ] = atoms {sel}")

    groups = group_ranges(len(case_dirs), a.replicas_per_job)
    ntomp = cpus_per_rank(max(len(g) for g in groups))
    for gi, members in enumerate(groups):
        sh = a.outdir / f"run_group_{gi:03d}.sh"
        sh.write_text(multidir_group_script(
            index=("../beads.ndx" if a.freeze else None), plumed=not a.freeze,
            case_dirs=[case_dirs[i] for i in members],
            structure_for=["seed.gro"] * len(members),
            topology=str(Path(a.topology).resolve()), ntomp=ntomp,
            n_gpus=a.gpus_per_node, use_server=False, mps=True))
        sh.chmod(0o755)
    (a.outdir / "submit.slurm").write_text(submit_script(
        campaign_dir=a.outdir, groups=groups, job_name="meanforce",
        hours=a.wall_hours, n_gpus=a.gpus_per_node,
        groups_per_task=a.groups_per_task))
    (a.outdir / "manifest.json").write_text(json.dumps(manifest, indent=1))

    print(f"wrote {len(case_dirs)} states in {len(groups)} group(s) of "
          f"<= {a.replicas_per_job}, ntomp={ntomp}")
    print(f"  NVT (pcoupl=no, tcoupl=v-rescale); min PBC margin "
          f"{np.min(margins):.1f} A (need {a.pbc_margin})")
    print(f"  sbatch {a.outdir}/submit.slurm")


if __name__ == "__main__":
    main()
