"""DISCOVER -> HARVEST stage 2: many short restrained AA replicas that HARVEST a region.

THE MEASUREMENT THAT MOTIVATES THIS (2026-08-08, ala2 bb6 alphaL):

    conformational decorrelation INSIDE alphaL, tau(phi,psi)  =   0.20 ps
    alphaL escape time (AA reference, median residence)       =  85    ps
    MetaD median alphaL residence                             =   1.3  ps

Within-basin decorrelation is ~425x faster than escape. Those are separate problems, and
conflating them is why the MetaD campaigns are inefficient: MetaD pays a full barrier
crossing to buy ~6 independent samples (1.3 ps / 0.2 ps) and then ejects the molecule.

Measured at a MATCHED dwell threshold (>=5 ps, the reference's own 5 ps resolution):
three MetaD campaigns yield ~500 genuine alphaL visits against the reference's 236 -- about
2x, not the 8.6x a naive boundary-crossing count suggests.

The fix is not a better bias. It is to STOP paying for crossings: seed inside the region and
restrain weakly so residence converts into samples. A 200 ps restrained replica yields
~1,000 decorrelated samples instead of ~6.

WHY A RESTRAINT IS LEGITIMATE HERE
    Force-matching labels come from the BIAS-FREE rerun, so the sampling bias never enters
    the dataset -- it only decides which configurations get labelled. The restraint acts on
    CG bead positions only, like every other term in this registry.

    It DOES bias the intra-basin distribution, so use SEVERAL umbrella centres tiling the
    region rather than one, and leave basin weights to assembly + REM.

WHAT THIS DELIBERATELY DOES NOT DO
    Raise the temperature. It would buy crossings cheaply, but hidden atomistic degrees of
    freedom would equilibrate at the wrong temperature and <F_AA | CG> would be
    systematically wrong -- violating the conditional-equilibration requirement.

SEEDS come from AA trajectories of a previous DISCOVERY campaign (biased.trr), not from the
reference: the reference has only 236 independent alphaL visits, while the MetaD campaigns
supply tens of thousands of diverse in-region frames. Selection is farthest-point in the
region's CVs so the seeds tile it rather than clustering.
"""
from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path

import numpy as np

from .mapping import dihedral_deg, get_mapping, wrap_deg

REPO = Path(__file__).resolve().parents[1]
GMX_MODULES = "Stages/2025 GCC/13.3.0 ParaStationMPI/5.11.0-1 GROMACS/2024.3-PLUMED-2.9.3"

RUN_CASE = """#!/bin/bash
# Generated by sampling/build_harvest_campaign.py -- do not edit by hand.
set -Eeuo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
cd "$HERE"

module --force purge
module load Stages/2025
module load GCC/13.3.0 ParaStationMPI/5.11.0-1
module load GROMACS/2024.3-PLUMED-2.9.3

gmx grompp -f production.mdp -c seed.gro -p {topology} -o biased.tpr -maxwarn 2
gmx mdrun -deffnm biased -plumed plumed.dat -ntmpi 1 -ntomp {ntomp}

# Bias-free force rerun -- MANDATORY. The umbrella force must never reach the dataset.
gmx mdrun -s biased.tpr -rerun biased.trr -deffnm unbiased_forces -ntmpi 1 -ntomp {ntomp}
echo "harvest case {case} complete"
"""

PLUMED = """# Harvest umbrella: hold the molecule in the target region so residence becomes samples.
# KAPPA is deliberately WEAK -- enough to stop escape, not enough to freeze the basin.
phi: TORSION ATOMS={phi_atoms}
psi: TORSION ATOMS={psi_atoms}
RESTRAINT ARG=phi,psi AT={phi_c:.4f},{psi_c:.4f} KAPPA={kappa:.1f},{kappa:.1f} LABEL=umb
PRINT ARG=phi,psi,umb.bias FILE=colvar.dat STRIDE={print_stride}
"""


def _farthest_point(phi, psi, k, rng):
    """Tile the region rather than cluster: maximise minimum pairwise CV distance."""
    sel = [int(rng.integers(len(phi)))]
    d2 = lambda i, j: (np.minimum(abs(phi[i] - phi[j]), 360 - abs(phi[i] - phi[j])) ** 2
                       + np.minimum(abs(psi[i] - psi[j]), 360 - abs(psi[i] - psi[j])) ** 2)
    mind = d2(np.arange(len(phi)), sel[0])
    while len(sel) < k:
        nxt = int(np.argmax(mind))
        sel.append(nxt)
        mind = np.minimum(mind, d2(np.arange(len(phi)), nxt))
    return np.array(sel)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--discovery-campaign", type=Path, required=True,
                    help="campaign dir whose replica_*/biased.trr supply AA seed frames")
    ap.add_argument("--frames-npz", type=Path, required=True,
                    help="collected CG frames of that campaign (frame order must match)")
    ap.add_argument("--n-replicas", type=int, default=96)
    ap.add_argument("--region", required=True, metavar="phi0:phi1:psi0:psi1")
    ap.add_argument("--umbrella-centres", type=int, default=4,
                    help="tile the region with this many restraint centres; ONE centre "
                         "would bias the intra-region distribution toward it")
    ap.add_argument("--kappa", type=float, default=50.0,
                    help="kJ/mol/rad^2. Weak by design: stop escape, do not freeze the basin")
    ap.add_argument("--ps-per-case", type=float, default=200.0)
    ap.add_argument("--output-ps", type=float, default=0.5,
                    help="frame spacing. tau(phi,psi) inside alphaL is 0.20 ps, so 0.5 ps "
                         "is still near-independent at 5x less data than the usual 0.1 ps")
    ap.add_argument("--topology", required=True)
    ap.add_argument("--mdp", type=Path,
                    default=REPO / "sampling/campaigns/production_298K_dt1fs.mdp")
    ap.add_argument("--gmx", required=True)
    ap.add_argument("--ntomp", type=int, default=8)
    ap.add_argument("--mapping", default="ala2_backbone_cb_6")
    ap.add_argument("--seed", type=int, default=20260808)
    a = ap.parse_args()

    m = get_mapping(a.mapping)
    p0, p1, s0, s1 = (float(x) for x in a.region.split(":"))
    R = np.load(a.frames_npz)["R"].astype(np.float64)
    cv = lambda n: wrap_deg(dihedral_deg(R, m.cvs[n].bead_indices) + m.cvs[n].shift_deg)
    phi, psi = cv("phi"), cv("psi")
    inreg = np.flatnonzero((phi > p0) & (phi < p1) & (psi > s0) & (psi < s1))
    if len(inreg) < a.n_replicas:
        raise SystemExit(f"only {len(inreg)} frames in region, need {a.n_replicas}")
    rng = np.random.default_rng(a.seed)
    pick = inreg[_farthest_point(phi[inreg], psi[inreg], a.n_replicas, rng)]
    print(f"{len(inreg)} frames in region -> {len(pick)} farthest-point seeds")
    print(f"  seed phi {phi[pick].min():.1f}..{phi[pick].max():.1f}, "
          f"psi {psi[pick].min():.1f}..{psi[pick].max():.1f}")

    reps = sorted(p for p in a.discovery_campaign.glob("replica_*") if p.is_dir())
    per = len(R) // len(reps)          # collected frames are replica-concatenated in order
    dt_fs = 1.0
    nsteps = int(a.ps_per_case * 1000 / dt_fs)
    nst_out = int(a.output_ps * 1000 / dt_fs)
    base = a.mdp.read_text()
    mdp = []
    for line in base.splitlines():
        t = line.strip()
        if t.startswith("nsteps"):
            line = f"nsteps                  = {nsteps} ; {a.ps_per_case} ps"
        elif t.startswith("nstxout ") or t.startswith("nstfout"):
            line = f"{t.split()[0]:<24}= {nst_out}          ; {a.output_ps} ps"
        elif t.startswith("gen_vel") or t.startswith("continuation"):
            continue
        mdp.append(line)
    mdp_body = "\n".join(mdp)

    # umbrella centres tiling the region
    cs = np.linspace(p0 + (p1 - p0) / 8, p1 - (p1 - p0) / 8, max(1, a.umbrella_centres))
    ss = np.full_like(cs, 0.5 * (s0 + s1))

    a.out.mkdir(parents=True, exist_ok=True)
    cases = []
    for i, fidx in enumerate(pick):
        rep, loc = reps[int(fidx) // per], int(fidx) % per
        d = a.out / f"case_{i:03d}"
        d.mkdir(parents=True, exist_ok=True)
        # extract that AA frame; discovery frames were written every 0.1 ps after a 20 ps discard
        t_ps = (loc + 200) * 0.1
        # GROMACS lives in the 2025 module stack and the venv in 2026; loading either
        # purges the other, so an absolute gmx path alone fails with rc=127. Same
        # bash -lc + module load wrapper collect.py uses.
        cmd = (f"module --force purge >/dev/null 2>&1; "
               f"module load {GMX_MODULES} >/dev/null 2>&1; "
               f"{a.gmx} trjconv -f {rep/'biased.trr'} -s {rep/'biased.tpr'} "
               f"-o {d/'seed.gro'} -dump {t_ps} -pbc whole")
        proc = subprocess.run(["bash", "-lc", cmd], input="0\n", text=True,
                              capture_output=True)
        if proc.returncode != 0 or not (d / "seed.gro").exists():
            raise SystemExit(f"{d.name}: trjconv failed (rc={proc.returncode})\n"
                             + proc.stderr[-1500:])
        ci = i % len(cs)
        (d / "plumed.dat").write_text(PLUMED.format(
            phi_atoms=",".join(str(x) for x in m.cvs["phi"].atom_indices_1based(m)),
            psi_atoms=",".join(str(x) for x in m.cvs["psi"].atom_indices_1based(m)),
            # PLUMED's TORSION == our +180 convention DIRECTLY, so pass the target as-is.
            # Our dihedral_deg uses b0 = p1 - p0 where IUPAC uses p0 - p1, a 180 offset --
            # which is exactly what mapping.shift_deg=180 compensates for. Subtracting the
            # shift here double-corrects and aims the umbrella at the MIRROR phi: the first
            # harvest run (job 1301394) targeted phi=-150 instead of +30 and produced 0
            # alphaL frames out of 34,656, every one landing in beta/PPII instead.
            # VERIFIED: collected frames' our-convention phi mean -145.1 vs PLUMED colvar
            # mean -144.2 -- the two conventions agree with no shift.
            phi_c=np.deg2rad(cs[ci]),
            psi_c=np.deg2rad(ss[ci]),
            kappa=a.kappa, print_stride=100))
        (d / "production.mdp").write_text(
            mdp_body + f"\ngen_vel                 = yes\ngen_temp                = 298\n"
                       f"gen_seed                = {a.seed + i}\ncontinuation            = no\n")
        rc = d / "run_case.sh"
        rc.write_text(RUN_CASE.format(topology=a.topology, ntomp=a.ntomp, case=f"case_{i:03d}"))
        rc.chmod(0o755)
        cases.append({"case": d.name, "seed_frame": int(fidx), "replica": rep.name,
                      "phi": float(phi[fidx]), "psi": float(psi[fidx]),
                      "umbrella_phi": float(cs[ci]), "umbrella_psi": float(ss[ci])})

    (a.out / "campaign.json").write_text(json.dumps({
        "name": a.out.name, "mapping": a.mapping, "stage": "harvest",
        "region": [p0, p1, s0, s1], "n_cases": len(cases),
        "kappa_kJ_mol_rad2": a.kappa, "umbrella_centres": list(map(float, cs)),
        "ps_per_case": a.ps_per_case, "output_ps": a.output_ps, "dt_fs": dt_fs,
        "required_discard_ps": 20.0,
        "discovery_campaign": str(a.discovery_campaign),
        "labels": "unbiased_forces.trr (bias-free rerun); umbrella force excluded",
        "cases": cases}, indent=2))
    slurm = a.out / "submit.slurm"
    slurm.write_text(f"""#!/bin/bash
#SBATCH --job-name={a.out.name[:14]}
#SBATCH --account=cameo
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=16
#SBATCH --time=01:00:00
#SBATCH --partition=booster
#SBATCH --gres=gpu:1
#SBATCH --array=0-{len(cases)-1}%32
#SBATCH --output={a.out}/%A_%a.out
#SBATCH --error={a.out}/%A_%a.err
set -Eeuo pipefail
cd "{a.out}/case_$(printf '%03d' "$SLURM_ARRAY_TASK_ID")"
srun --ntasks-per-node=1 ./run_case.sh
""")
    print(f"wrote {len(cases)} cases to {a.out}")
    print(f"  {a.ps_per_case} ps each at dt={dt_fs}fs, {a.output_ps} ps output -> "
          f"~{int(a.ps_per_case/a.output_ps)} frames/case, "
          f"~{int(len(cases)*a.ps_per_case/a.output_ps)} total")
    print(f"  submit: sbatch {slurm}")


if __name__ == "__main__":
    main()
