"""DISCOVER -> HARVEST stage 2: many short restrained AA replicas that HARVEST a region.

THE MEASUREMENT THAT MOTIVATES THIS (2026-08-08, ala2 bb6 alphaL):

    conformational decorrelation INSIDE alphaL, tau(phi,psi)  =   0.20 ps
    alphaL escape time (AA reference, median residence)       =  85    ps
    MetaD median alphaL residence                             =   1.3  ps

Within-basin decorrelation is ~425x faster than escape. Those are separate problems, and
conflating them is why the MetaD campaigns are inefficient: MetaD pays a full barrier
crossing to buy ~6 independent samples (1.3 ps / 0.2 ps) and then ejects the molecule.

Measured at a MATCHED dwell threshold (>=5 ps, the reference's own 5 ps resolution):
three MetaD campaigns yield ~500 genuine alphaL visits against the reference's 236 -- about
2x, not the 8.6x a naive boundary-crossing count suggests.

The fix is not a better bias. It is to STOP paying for crossings: seed inside the region and
restrain weakly so residence converts into samples. A 200 ps restrained replica yields
~1,000 decorrelated samples instead of ~6.

WHY A RESTRAINT IS LEGITIMATE HERE
    Force-matching labels come from the BIAS-FREE rerun, so the sampling bias never enters
    the dataset -- it only decides which configurations get labelled. The restraint acts on
    CG bead positions only, like every other term in this registry.

    It DOES bias the intra-basin distribution, so use SEVERAL umbrella centres tiling the
    region rather than one, and leave basin weights to assembly + REM.

WHAT THIS DELIBERATELY DOES NOT DO
    Raise the temperature. It would buy crossings cheaply, but hidden atomistic degrees of
    freedom would equilibrate at the wrong temperature and <F_AA | CG> would be
    systematically wrong -- violating the conditional-equilibration requirement.

SEEDS come from AA trajectories of a previous DISCOVERY campaign (biased.trr), not from the
reference: the reference has only 236 independent alphaL visits, while the MetaD campaigns
supply tens of thousands of diverse in-region frames. Selection is farthest-point in the
region's CVs so the seeds tile it rather than clustering.

SIZING THE RESTRAINT -- the v1 failure, and the rule that replaces it (2026-08-11)
    v1 ran KAPPA=50 kJ/mol/rad^2 on phi AND psi, with every case at the same psi centre.
    Both choices were wrong, and the campaign produced 34,656 decorrelated frames that did
    NOT reduce the model's alphaL force bias at all, because they re-sampled the basin CORE
    that the reference already covers:

        commanded phi   30     50     70     90
        achieved  phi   45.1   51.5   57.3   63.2      <- 60 deg commanded -> 18 deg achieved
        psi sd:   harvest 10.4 vs reference 19.2       <- compressed ~2x by the psi restraint

    A harmonic restraint has width sqrt(kT/kappa); at 298 K (kT = 2.478 kJ/mol) KAPPA=50
    gives 12.8 deg -- COMPARABLE TO THE BASIN'S OWN WIDTH. Such a restraint is a tether, not
    a clamp: it cannot displace the molecule against the free-energy gradient, so every
    window slides back to the free-energy minimum.

    RULES:
    1. Size kappa from the FES gradient, not a default. From an observed offset d at
       kappa_old, the local restoring force is kappa_old*d; to hold within e use
       kappa >= kappa_old*d/e. For ala2 alphaL that is ~270 minimum; use 300-500.
    2. Windows must OVERLAP. Stiff windows are narrow (kappa=400 -> sd 4.5 deg), so spacing
       must be ~1.5x the width or the tiling has gaps. Tiling 20..100 deg needs ~12 centres,
       not 4.
    3. Only clamp the coordinate you are tiling. For a coordinate whose SPREAD you want to
       reproduce, leave it FREE (or match kappa = kT/sigma^2 to the target spread). Clamping
       phi already prevents escape; psi does not need restraining.
    4. PILOT FIRST. `--check <campaign_dir>` reads colvar.dat and prints achieved-vs-commanded
       per window. Run a short pilot and check it before spending the full budget.

    Independence is necessary but NOT sufficient: samples must TILE the region, not pile up
    at its minimum.
"""
from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path

import numpy as np

from .mapping import dihedral_deg, get_mapping, wrap_deg

REPO = Path(__file__).resolve().parents[1]
GMX_MODULES = "Stages/2025 GCC/13.3.0 ParaStationMPI/5.11.0-1 GROMACS/2024.3-PLUMED-2.9.3"

RUN_CASE = """#!/bin/bash
# Generated by sampling/build_harvest_campaign.py -- do not edit by hand.
set -Eeuo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
cd "$HERE"

module --force purge
module load Stages/2025
module load GCC/13.3.0 ParaStationMPI/5.11.0-1
module load GROMACS/2024.3-PLUMED-2.9.3

gmx grompp -f production.mdp -c seed.gro -p {topology} -o biased.tpr -maxwarn 2
gmx mdrun -deffnm biased -plumed plumed.dat -ntmpi 1 -ntomp {ntomp}

# Bias-free force rerun -- MANDATORY. The umbrella force must never reach the dataset.
gmx mdrun -s biased.tpr -rerun biased.trr -deffnm unbiased_forces -ntmpi 1 -ntomp {ntomp}
echo "harvest case {case} complete"
"""

# v1 used KAPPA=50 on BOTH phi and psi and put every case at the same psi centre.
# Both were wrong -- see "SIZING THE RESTRAINT" in the module docstring.
PLUMED_PHI_ONLY = """# Harvest umbrella: CLAMP phi to tile the region; leave psi FREE to equilibrate.
# phi is clamped because it is the coordinate that defines the region and the one the
# molecule escapes along. psi is left free ON PURPOSE: we want its natural conditional
# distribution at each phi, not a compressed one (v1 restrained it and cut its spread ~2x).
phi: TORSION ATOMS={phi_atoms}
psi: TORSION ATOMS={psi_atoms}
RESTRAINT ARG=phi AT={phi_c:.4f} KAPPA={kappa_phi:.1f} LABEL=umb
PRINT ARG=phi,psi,umb.bias FILE=colvar.dat STRIDE={print_stride}
"""

PLUMED_BOTH = """# Harvest umbrella: clamp phi AND psi (2-D tiling).
phi: TORSION ATOMS={phi_atoms}
psi: TORSION ATOMS={psi_atoms}
RESTRAINT ARG=phi,psi AT={phi_c:.4f},{psi_c:.4f} KAPPA={kappa_phi:.1f},{kappa_psi:.1f} LABEL=umb
PRINT ARG=phi,psi,umb.bias FILE=colvar.dat STRIDE={print_stride}
"""


def _farthest_point(phi, psi, k, rng):
    """Tile the region rather than cluster: maximise minimum pairwise CV distance."""
    sel = [int(rng.integers(len(phi)))]
    d2 = lambda i, j: (np.minimum(abs(phi[i] - phi[j]), 360 - abs(phi[i] - phi[j])) ** 2
                       + np.minimum(abs(psi[i] - psi[j]), 360 - abs(psi[i] - psi[j])) ** 2)
    mind = d2(np.arange(len(phi)), sel[0])
    while len(sel) < k:
        nxt = int(np.argmax(mind))
        sel.append(nxt)
        mind = np.minimum(mind, d2(np.arange(len(phi)), nxt))
    return np.array(sel)


def check_campaign(root: Path) -> int:
    """ACHIEVED vs COMMANDED per window, straight from PLUMED's own colvar.dat.

    Run this on a short pilot BEFORE committing the full budget. It is the check whose
    absence let v1 spend 19.2 ns of AA re-sampling the basin core: every case ran, every
    case wrote frames, and nothing reported that the windows had slid off their centres.
    Works on a partial campaign -- colvar.dat is written every 100 steps.
    """
    cam = json.loads((root / "campaign.json").read_text())
    by_centre: dict[float, list] = {}
    n_missing = 0
    for case in cam["cases"]:
        f = root / case["case"] / "colvar.dat"
        if not f.exists():
            n_missing += 1
            continue
        rows = np.loadtxt(f, comments="#")
        if rows.ndim < 2 or len(rows) < 2:
            n_missing += 1
            continue
        half = len(rows) // 2                       # drop the first half as equilibration
        ph = np.degrees(rows[half:, 1])
        ps = np.degrees(rows[half:, 2])
        by_centre.setdefault(float(case["umbrella_phi"]), []).append((ph, ps))
    if not by_centre:
        print(f"no colvar.dat found under {root} -- has the campaign run?")
        return 1
    kappa = cam.get("kappa_phi_kJ_mol_rad2", cam.get("kappa_kJ_mol_rad2"))
    print(f"campaign {cam['name']}  kappa_phi={kappa}  "
          f"psi_restrained={cam.get('psi_restrained')}  ({n_missing} case(s) without data)")
    print(f"\n{'commanded phi':>13} {'n':>4} {'achieved <phi>':>15} {'offset':>8} "
          f"{'sd(phi)':>8} {'<psi>':>8} {'sd(psi)':>8}")
    worst = 0.0
    for c in sorted(by_centre):
        ph = np.concatenate([x[0] for x in by_centre[c]])
        ps = np.concatenate([x[1] for x in by_centre[c]])
        off = ph.mean() - c
        worst = max(worst, abs(off))
        print(f"{c:13.1f} {len(by_centre[c]):4d} {ph.mean():15.1f} {off:+8.1f} "
              f"{ph.std():8.1f} {ps.mean():8.1f} {ps.std():8.1f}")
    print(f"\nworst |offset| = {worst:.1f} deg")
    if worst > 10.0:
        print("  !! FAIL: windows are sliding off their centres -- kappa_phi is too soft.\n"
              f"     Local restoring force ~ {kappa}*{np.radians(worst):.3f} rad = "
              f"{kappa*np.radians(worst):.1f} kJ/mol/rad.\n"
              f"     To hold within 5 deg use kappa_phi >= "
              f"{kappa*np.radians(worst)/np.radians(5.0):.0f}. DO NOT run the full campaign.")
        return 1
    print("  OK: windows hold their commanded centres. Safe to run the full campaign.")
    return 0


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", type=Path, default=None,
                    help="analyse an existing (possibly partial) campaign dir: achieved vs "
                         "commanded phi per window, then exit. Run this on a pilot FIRST.")
    ap.add_argument("--out", type=Path)
    ap.add_argument("--discovery-campaign", type=Path,
                    help="campaign dir whose replica_*/biased.trr supply AA seed frames")
    ap.add_argument("--frames-npz", type=Path,
                    help="collected CG frames of that campaign (frame order must match)")
    ap.add_argument("--n-replicas", type=int, default=96)
    ap.add_argument("--region", metavar="phi0:phi1:psi0:psi1")
    ap.add_argument("--umbrella-centres", type=int, default=12,
                    help="phi restraint centres tiling the region. Must be dense enough that "
                         "adjacent windows OVERLAP: spacing ~1.5x sqrt(kT/kappa_phi). v1 used "
                         "4 centres with a soft kappa and left 60%% of the range unsampled")
    ap.add_argument("--kappa-phi", type=float, default=400.0,
                    help="kJ/mol/rad^2 on phi. Must CLAMP (hold against the FES gradient), "
                         "not tether -- see SIZING THE RESTRAINT in the module docstring. "
                         "v1's 50.0 let every window slide back to the basin minimum")
    ap.add_argument("--kappa-psi", type=float, default=0.0,
                    help="kJ/mol/rad^2 on psi. DEFAULT 0 = psi UNRESTRAINED, which is what "
                         "you want when the goal is to reproduce psi's natural conditional "
                         "spread. Clamping phi already prevents escape")
    ap.add_argument("--psi-centres", type=int, default=1,
                    help="only used when --kappa-psi > 0: psi centres tiling the region")
    ap.add_argument("--ps-per-case", type=float, default=200.0)
    ap.add_argument("--output-ps", type=float, default=0.5,
                    help="frame spacing. tau(phi,psi) inside alphaL is 0.20 ps, so 0.5 ps "
                         "is still near-independent at 5x less data than the usual 0.1 ps")
    ap.add_argument("--topology")
    ap.add_argument("--mdp", type=Path,
                    default=REPO / "sampling/campaigns/production_298K_dt1fs.mdp")
    ap.add_argument("--gmx")
    ap.add_argument("--ntomp", type=int, default=8)
    ap.add_argument("--mapping", default="ala2_backbone_cb_6")
    ap.add_argument("--launch", choices=("per-case", "multidir"), default="per-case",
                    help="per-case: one SLURM array task per case (one GPU each, most of the "
                         "node idle). multidir: pack --replicas-per-job cases into one "
                         "gmx_mpi invocation sharing the node's GPUs")
    ap.add_argument("--replicas-per-job", type=int, default=8,
                    help="multidir group size. Smaller groups bound the damage from a "
                         "crashed rank, which aborts its whole mdrun")
    ap.add_argument("--gpus-per-node", type=int, default=4)
    ap.add_argument("--seed", type=int, default=20260808)
    a = ap.parse_args()

    if a.check is not None:
        raise SystemExit(check_campaign(a.check))
    missing = [f"--{k.replace('_','-')}" for k in
               ("out", "discovery_campaign", "frames_npz", "region", "topology", "gmx")
               if getattr(a, k) is None]
    if missing:
        ap.error("required unless --check is given: " + ", ".join(missing))

    m = get_mapping(a.mapping)
    p0, p1, s0, s1 = (float(x) for x in a.region.split(":"))
    R = np.load(a.frames_npz)["R"].astype(np.float64)
    cv = lambda n: wrap_deg(dihedral_deg(R, m.cvs[n].bead_indices) + m.cvs[n].shift_deg)
    phi, psi = cv("phi"), cv("psi")
    inreg = np.flatnonzero((phi > p0) & (phi < p1) & (psi > s0) & (psi < s1))
    if len(inreg) < a.n_replicas:
        raise SystemExit(f"only {len(inreg)} frames in region, need {a.n_replicas}")
    rng = np.random.default_rng(a.seed)
    pick = inreg[_farthest_point(phi[inreg], psi[inreg], a.n_replicas, rng)]
    print(f"{len(inreg)} frames in region -> {len(pick)} farthest-point seeds")
    print(f"  seed phi {phi[pick].min():.1f}..{phi[pick].max():.1f}, "
          f"psi {psi[pick].min():.1f}..{psi[pick].max():.1f}")

    reps = sorted(p for p in a.discovery_campaign.glob("replica_*") if p.is_dir())
    per = len(R) // len(reps)          # collected frames are replica-concatenated in order
    dt_fs = 1.0
    nsteps = int(a.ps_per_case * 1000 / dt_fs)
    nst_out = int(a.output_ps * 1000 / dt_fs)
    base = a.mdp.read_text()
    mdp = []
    for line in base.splitlines():
        t = line.strip()
        if t.startswith("nsteps"):
            line = f"nsteps                  = {nsteps} ; {a.ps_per_case} ps"
        elif t.startswith("nstxout ") or t.startswith("nstfout"):
            line = f"{t.split()[0]:<24}= {nst_out}          ; {a.output_ps} ps"
        elif t.startswith("gen_vel") or t.startswith("continuation"):
            continue
        mdp.append(line)
    mdp_body = "\n".join(mdp)

    # Umbrella centres tiling the region. phi always; psi only if it is restrained at all
    # (with --kappa-psi 0 the psi "centre" is unused and must not narrow the sampling).
    kT_kJ = 0.0083144621 * 298.0
    n_phi = max(1, a.umbrella_centres)
    cs = np.linspace(p0 + (p1 - p0) / 8, p1 - (p1 - p0) / 8, n_phi)
    if a.kappa_psi > 0:
        n_psi = max(1, a.psi_centres)
        ss_grid = (np.linspace(s0 + (s1 - s0) / 8, s1 - (s1 - s0) / 8, n_psi) if n_psi > 1
                   else np.array([0.5 * (s0 + s1)]))
    else:
        ss_grid = np.array([0.5 * (s0 + s1)])          # recorded only; no psi RESTRAINT emitted
    centres = [(float(c), float(s)) for c in cs for s in ss_grid]

    # Overlap check: stiff windows are narrow, so a coarse grid leaves holes.
    sd_phi = np.degrees(np.sqrt(kT_kJ / a.kappa_phi))
    spacing = (cs[1] - cs[0]) if len(cs) > 1 else float(p1 - p0)
    print(f"phi windows: {len(cs)} centres {cs[0]:.1f}..{cs[-1]:.1f}, spacing {spacing:.1f} deg, "
          f"width sd {sd_phi:.1f} deg (kappa_phi {a.kappa_phi:g})")
    if spacing > 1.5 * sd_phi:
        print(f"  !! WARNING: spacing {spacing:.1f} > 1.5*sd {1.5*sd_phi:.1f} -- windows do NOT "
              f"overlap; the tiling will have gaps. Raise --umbrella-centres to "
              f"~{int(np.ceil((p1-p0)/(1.5*sd_phi)))+1} or lower --kappa-phi.")
    print(f"psi: {'FREE (unrestrained)' if a.kappa_psi <= 0 else f'{len(ss_grid)} centres, kappa {a.kappa_psi:g}'}"
          f"   -> {len(centres)} distinct windows over {a.n_replicas} cases")

    # Pair each seed with a NEARBY window rather than round-robin. A stiff restraint whose
    # centre is far from its seed yanks the molecule on step 1 (kappa*dphi: at kappa=400 a
    # 48 deg mismatch is ~335 kJ/mol/rad) and wastes the equilibration window. Both seeds and
    # centres tile the same phi range, so rank-ordering both and pairing by rank is
    # near-optimal and keeps the windows exactly balanced.
    order = np.argsort(phi[pick])
    win_of_seed = np.empty(len(pick), dtype=int)
    win_of_seed[order] = (np.arange(len(pick)) * len(centres)) // len(pick)
    mism = np.abs(phi[pick] - np.array([centres[w][0] for w in win_of_seed]))
    print(f"seed->window pairing: |phi_seed - phi_centre| mean {mism.mean():.1f} deg, "
          f"max {mism.max():.1f} deg")

    a.out.mkdir(parents=True, exist_ok=True)
    cases = []
    for i, fidx in enumerate(pick):
        rep, loc = reps[int(fidx) // per], int(fidx) % per
        d = a.out / f"case_{i:03d}"
        d.mkdir(parents=True, exist_ok=True)
        # extract that AA frame; discovery frames were written every 0.1 ps after a 20 ps discard
        t_ps = (loc + 200) * 0.1
        # GROMACS lives in the 2025 module stack and the venv in 2026; loading either
        # purges the other, so an absolute gmx path alone fails with rc=127. Same
        # bash -lc + module load wrapper collect.py uses.
        cmd = (f"module --force purge >/dev/null 2>&1; "
               f"module load {GMX_MODULES} >/dev/null 2>&1; "
               f"{a.gmx} trjconv -f {rep/'biased.trr'} -s {rep/'biased.tpr'} "
               f"-o {d/'seed.gro'} -dump {t_ps} -pbc whole")
        proc = subprocess.run(["bash", "-lc", cmd], input="0\n", text=True,
                              capture_output=True)
        if proc.returncode != 0 or not (d / "seed.gro").exists():
            raise SystemExit(f"{d.name}: trjconv failed (rc={proc.returncode})\n"
                             + proc.stderr[-1500:])
        ci = int(win_of_seed[i])
        phi_c_deg, psi_c_deg = centres[ci]
        tmpl = PLUMED_BOTH if a.kappa_psi > 0 else PLUMED_PHI_ONLY
        (d / "plumed.dat").write_text(tmpl.format(
            phi_atoms=",".join(str(x) for x in m.cvs["phi"].atom_indices_1based(m)),
            psi_atoms=",".join(str(x) for x in m.cvs["psi"].atom_indices_1based(m)),
            # PLUMED's TORSION == our +180 convention DIRECTLY, so pass the target as-is.
            # Our dihedral_deg uses b0 = p1 - p0 where IUPAC uses p0 - p1, a 180 offset --
            # which is exactly what mapping.shift_deg=180 compensates for. Subtracting the
            # shift here double-corrects and aims the umbrella at the MIRROR phi: the first
            # harvest run (job 1301394) targeted phi=-150 instead of +30 and produced 0
            # alphaL frames out of 34,656, every one landing in beta/PPII instead.
            # VERIFIED: collected frames' our-convention phi mean -145.1 vs PLUMED colvar
            # mean -144.2 -- the two conventions agree with no shift.
            phi_c=np.deg2rad(phi_c_deg),
            psi_c=np.deg2rad(psi_c_deg),
            kappa_phi=a.kappa_phi, kappa_psi=a.kappa_psi, print_stride=100))
        (d / "production.mdp").write_text(
            mdp_body + f"\ngen_vel                 = yes\ngen_temp                = 298\n"
                       f"gen_seed                = {a.seed + i}\ncontinuation            = no\n")
        rc = d / "run_case.sh"
        rc.write_text(RUN_CASE.format(topology=a.topology, ntomp=a.ntomp, case=f"case_{i:03d}"))
        rc.chmod(0o755)
        cases.append({"case": d.name, "seed_frame": int(fidx), "replica": rep.name,
                      "phi": float(phi[fidx]), "psi": float(psi[fidx]),
                      "umbrella_phi": phi_c_deg,
                      "umbrella_psi": (psi_c_deg if a.kappa_psi > 0 else None)})

    (a.out / "campaign.json").write_text(json.dumps({
        "name": a.out.name, "mapping": a.mapping, "stage": "harvest",
        "region": [p0, p1, s0, s1], "n_cases": len(cases),
        "kappa_phi_kJ_mol_rad2": a.kappa_phi,
        "kappa_psi_kJ_mol_rad2": a.kappa_psi,
        "psi_restrained": bool(a.kappa_psi > 0),
        "phi_window_sd_deg": float(sd_phi),
        "umbrella_centres": list(map(float, cs)),
        "umbrella_psi_centres": (list(map(float, ss_grid)) if a.kappa_psi > 0 else None),
        "ps_per_case": a.ps_per_case, "output_ps": a.output_ps, "dt_fs": dt_fs,
        "required_discard_ps": 20.0,
        "discovery_campaign": str(a.discovery_campaign),
        "labels": "unbiased_forces.trr (bias-free rerun); umbrella force excluded",
        "cases": cases}, indent=2))
    slurm = a.out / "submit.slurm"
    if a.launch == "multidir":
        # Harvest cases are pure PLUMED (an umbrella; no bias server), so packing them is
        # just a launch change -- see sampling/launch.py for why gmx_mpi and why groups.
        from .launch import cpus_per_rank, group_ranges, multidir_group_script, submit_script

        groups = group_ranges(len(cases), int(a.replicas_per_job))
        ntomp = cpus_per_rank(max(len(g) for g in groups))
        for gi, members in enumerate(groups):
            script = a.out / f"run_group_{gi:03d}.sh"
            script.write_text(multidir_group_script(
                case_dirs=[f"case_{i:03d}" for i in members],
                structure_for=["seed.gro"] * len(members),   # extracted per case at build time
                topology=a.topology, ntomp=ntomp,
                n_gpus=int(a.gpus_per_node), use_server=False))
            script.chmod(0o755)
        slurm.write_text(submit_script(campaign_dir=a.out, groups=groups,
                                       job_name=a.out.name, hours=1.0,
                                       n_gpus=int(a.gpus_per_node)))
        print(f"  launch: multidir, {len(groups)} group(s) of up to {a.replicas_per_job} "
              f"cases, ntomp={ntomp}")
    else:
        slurm.write_text(f"""#!/bin/bash
#SBATCH --job-name={a.out.name[:14]}
#SBATCH --account=cameo
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=16
#SBATCH --time=01:00:00
#SBATCH --partition=booster
#SBATCH --gres=gpu:1
#SBATCH --array=0-{len(cases)-1}%32
#SBATCH --output={a.out}/%A_%a.out
#SBATCH --error={a.out}/%A_%a.err
set -Eeuo pipefail
cd "{a.out}/case_$(printf '%03d' "$SLURM_ARRAY_TASK_ID")"
srun --ntasks-per-node=1 ./run_case.sh
""")
    print(f"wrote {len(cases)} cases to {a.out}")
    print(f"  {a.ps_per_case} ps each at dt={dt_fs}fs, {a.output_ps} ps output -> "
          f"~{int(a.ps_per_case/a.output_ps)} frames/case, "
          f"~{int(len(cases)*a.ps_per_case/a.output_ps)} total")
    print(f"  submit: sbatch {slurm}")


if __name__ == "__main__":
    main()
