#!/usr/bin/env python3
"""Generate a CG-biased enhanced-sampling campaign from one YAML.

Writes, per replica: a PLUMED input, a bias-server config, and a run script that
starts the server, runs biased MD, then reruns forces WITHOUT the bias so the exported
labels are physical.

    python -m sampling.cases --config sampling/campaigns/ala2_bb6_pilot.yaml

The bias-free rerun is not optional. Biased dynamics saves f_AA + f_bias; force matching
must train on f_AA alone, or the model learns the sampler. See
KB DESIGN/MLCG_TEACHER_BIAS_SAMPLING.md ## Bias-Free Training Labels.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
from pathlib import Path
from typing import Any, Dict

import yaml

from .mapping import get_mapping

REPO = Path(__file__).resolve().parent.parent
PLUGIN_SO = REPO / "sampling" / "plugin" / "CGBias.so"


PLUMED_TEMPLATE = """\
# Generated by sampling/cases.py -- do not edit by hand.
# replica {replica}   mapping {mapping}   {n_beads} beads
LOAD FILE={plugin_so}

WHOLEMOLECULES ENTITY0={atoms}

# All bias logic lives in the server; this action is transport only.
cgbias: CG_BIAS ATOMS={atoms} SOCKET={socket} RECOMPUTE_STRIDE={recompute_stride} TIMEOUT={socket_timeout}
BIASVALUE ARG=cgbias

# Monitoring CVs (not biased directly)
{cv_lines}
PRINT ARG={cv_names},cgbias FILE=colvar.dat STRIDE={print_stride}
"""


RUN_TEMPLATE_NATIVE = """\
#!/bin/bash
# Generated by sampling/cases.py (bias_backend: plumed) -- do not edit by hand.
#
# No bias server: every term in this campaign is evaluated inside PLUMED. That removes the
# Unix socket and the Python process from the MD timestep loop, worth a measured 1.86x
# (937.6 ns/day pure-PLUMED vs 505.0 ns/day over the socket, ala2 bb6).
set -Eeuo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
cd "$HERE"

module --force purge
module load Stages/2025
module load GCC/13.3.0 ParaStationMPI/5.11.0-1
module load GROMACS/2024.3-PLUMED-2.9.3

gmx grompp -f production.mdp -c {structure} -p {topology} -o biased.tpr -maxwarn 2
gmx mdrun -deffnm biased -plumed plumed.dat -ntmpi 1 -ntomp {ntomp}

# bias-free force rerun (MANDATORY for training labels; no -plumed here)
gmx mdrun -s biased.tpr -rerun biased.trr -deffnm unbiased_forces -ntmpi 1 -ntomp {ntomp}

echo "case {replica} complete (native PLUMED): biased.trr + unbiased_forces.trr"
"""


RUN_TEMPLATE = """\
#!/bin/bash
# Generated by sampling/cases.py -- do not edit by hand.
set -Eeuo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
cd "$HERE"

SOCKET="{socket}"
rm -f "$SOCKET"

# ---- 1. bias server (one per replica) --------------------------------------
source {repo}/env_setup/load_modules_2026.sh
source {repo}/../venv_cameocg_jupiter2026/bin/activate
export JAX_PLATFORMS=cpu          # teacher runs beside GROMACS on CPU
cd {repo}
python -m sampling.server --config "$HERE/server.yaml" --socket "$SOCKET" \\
    --log "$HERE/server_events.log" --io-timeout {socket_timeout} > "$HERE/server.log" 2>&1 &
SERVER_PID=$!
trap 'kill $SERVER_PID 2>/dev/null || true; rm -f "$SOCKET"' EXIT
cd "$HERE"

for _ in $(seq 1 120); do [ -S "$SOCKET" ] && break; sleep 1; done
[ -S "$SOCKET" ] || {{ echo "bias server never created $SOCKET" >&2; cat "$HERE/server.log" >&2; exit 1; }}

# ---- 2. biased production ---------------------------------------------------
module --force purge
module load Stages/2025
module load GCC/13.3.0 ParaStationMPI/5.11.0-1
module load GROMACS/2024.3-PLUMED-2.9.3

gmx grompp -f production.mdp -c {structure} -p {topology} -o biased.tpr -maxwarn 2
gmx mdrun -deffnm biased -plumed plumed.dat -ntmpi 1 -ntomp {ntomp}

# ---- 3. bias-free force rerun (MANDATORY for training labels) --------------
gmx mdrun -s biased.tpr -rerun biased.trr -deffnm unbiased_forces -ntmpi 1 -ntomp {ntomp}

echo "case {replica} complete: biased.trr + unbiased_forces.trr"
"""


#: Bias types that can be evaluated inside PLUMED with no Python in the timestep loop.
#: `local_inversion_umbrella` is NOT here on purpose: its CV is the normalised signed volume
#: chi, which PLUMED has no equivalent for -- a Cayley-Menger + CUSTOM reconstruction has an
#: ambiguous sign and a derivative that diverges as chi -> 0, exactly where the production
#: chi_target ladder ends. `mlcg_teacher` needs the JAX model. Both keep the socket route.
NATIVE_BIAS_TYPES = frozenset({"tica_regional", "tica_metad"})


def native_backend_supported(cfg: Dict[str, Any]) -> tuple[bool, list[str]]:
    """Can this campaign run without the Python bias server? Returns (ok, blocking types)."""
    blockers = sorted({str(b.get("type")) for b in cfg.get("biases", [])
                       if b.get("enabled", True) and str(b.get("type")) not in NATIVE_BIAS_TYPES})
    return (not blockers), blockers


def build_case(case_dir: Path, replica: int, cfg: Dict[str, Any]) -> None:
    if str(cfg.get("bias_backend", "python")).lower() == "plumed":
        return _build_case_native(case_dir, replica, cfg)
    return _build_case_python(case_dir, replica, cfg)


def _build_case_native(case_dir: Path, replica: int, cfg: Dict[str, Any]) -> None:
    """Campaign case with every bias expressed as native PLUMED input.

    Emits no `server.yaml` and no `LOAD FILE=CGBias.so` -- there is nothing for the plugin or
    the server to do. Refuses rather than silently dropping a term that has no native form.
    """
    from .biases.tica_regional import SmoothTICABias
    from .plumed_native import PlumedNativeBias, write_external_grid

    ok, blockers = native_backend_supported(cfg)
    if not ok:
        raise ValueError(
            f"bias_backend: plumed cannot express {blockers}. Supported natively: "
            f"{sorted(NATIVE_BIAS_TYPES)}. Use bias_backend: python for this campaign."
        )

    case_dir.mkdir(parents=True, exist_ok=True)
    mapping = get_mapping(cfg["mapping"])
    terms = {str(b["type"]): _resolve_per_replica(b, replica)
             for b in cfg["biases"] if b.get("enabled", True)}

    # Both native terms share one artifact so MetaD and the regional field cannot drift into
    # different coordinates -- the same invariant tica_metad enforces by reusing the NPZ.
    npz = next((t["bias_npz"] for t in terms.values() if "bias_npz" in t), None)
    if npz is None:
        raise ValueError("bias_backend: plumed requires a bias_npz on at least one term")
    bias = SmoothTICABias.load(npz)

    grid_rel = None
    if "tica_regional" in terms:
        # The tabulated field depends ONLY on the artifact, so it is written once at the
        # campaign root and shared by every replica: per-case copies cost ~25 MB and ~12 s
        # EACH (300 MB / 2.5 min for a 12-replica campaign) for byte-identical files. The
        # name carries a hash of the source so a per-replica `bias_npz` still gets its own
        # grid instead of silently reusing another replica's.
        digest = hashlib.sha256(str(npz).encode()).hexdigest()[:10]
        shared = case_dir.parent / f"tica_regional_grid_{digest}.dat"
        if not shared.exists():
            write_external_grid(bias, shared,
                                n_points=tuple(cfg.get("external_grid_points", (401, 401))),
                                pad=float(cfg.get("external_grid_pad", 0.15)))
        # relative: both run_case.sh and `-multidir` execute with the case dir as cwd
        grid_rel = f"../{shared.name}"

    metad = None
    if "tica_metad" in terms:
        t = terms["tica_metad"]
        metad = dict(height=float(t.get("height", 0.15)),
                     sigma=tuple(t.get("sigma", (0.15, 0.09))),
                     pace=int(t.get("pace", 500)),
                     bias_factor=float(t.get("bias_factor", 8.0)),
                     temperature=float(t.get("temperature", 298.0)),
                     equilibrate_steps=int(t.get("equilibrate_steps", 0)),
                     dt_ps=_mdp_dt_ps(Path(cfg["mdp"])))

    (case_dir / "plumed.dat").write_text(
        PlumedNativeBias(mapping=mapping, bias=bias).render(
            monitor_cvs=cfg.get("monitor_cvs", ["phi", "psi"]),
            use_regional="tica_regional" in terms,
            grid_path=grid_rel,
            metad=metad,
            print_stride=int(cfg.get("print_stride", 500)),
        )
    )

    run = case_dir / "run_case.sh"
    run.write_text(RUN_TEMPLATE_NATIVE.format(
        replica=replica, structure=_resolve_structure(cfg, replica),
        topology=cfg["topology"], ntomp=int(cfg.get("ntomp", 8))))
    run.chmod(0o755)
    _write_mdp(Path(cfg["mdp"]), case_dir / "production.mdp", replica, cfg)


def _build_case_python(case_dir: Path, replica: int, cfg: Dict[str, Any]) -> None:
    case_dir.mkdir(parents=True, exist_ok=True)
    mapping = get_mapping(cfg["mapping"])
    atoms = mapping.plumed_atom_selection()
    socket = str(Path(cfg.get("socket_dir", "/tmp")) / f"cgbias_{cfg['name']}_r{replica}.sock")

    cv_lines, cv_names = [], []
    for cv_name in cfg.get("monitor_cvs", ["phi", "psi"]):
        cv = mapping.cvs[cv_name]
        idx = ",".join(str(i) for i in cv.atom_indices_1based(mapping))
        cv_lines.append(f"{cv_name}: TORSION ATOMS={idx}")
        cv_names.append(cv_name)

    (case_dir / "plumed.dat").write_text(
        PLUMED_TEMPLATE.format(
            replica=replica,
            mapping=mapping.name,
            n_beads=mapping.n_beads,
            plugin_so=PLUGIN_SO,
            atoms=atoms,
            socket=socket,
            cv_lines="\n".join(cv_lines),
            cv_names=",".join(cv_names),
            print_stride=int(cfg.get("print_stride", 500)),
            recompute_stride=int(cfg.get("recompute_stride", 1)),
            socket_timeout=float(cfg.get("socket_timeout_s", 600.0)),
        )
    )

    server_cfg = {
        "mapping": mapping.name,
        "report_every": int(cfg.get("report_every", 500)),
        "biases": [_resolve_per_replica(b, replica) for b in cfg["biases"]],
    }
    (case_dir / "server.yaml").write_text(yaml.safe_dump(server_cfg, sort_keys=False))

    run = case_dir / "run_case.sh"
    run.write_text(
        RUN_TEMPLATE.format(
            replica=replica,
            socket=socket,
            repo=REPO,
            structure=_resolve_structure(cfg, replica),
            topology=cfg["topology"],
            ntomp=int(cfg.get("ntomp", 8)),
            socket_timeout=float(cfg.get("socket_timeout_s", 600.0)),
        )
    )
    run.chmod(0o755)

    mdp_src = Path(cfg["mdp"])
    _write_mdp(mdp_src, case_dir / "production.mdp", replica, cfg)


def _mdp_dt_ps(mdp: Path) -> float:
    for line in mdp.read_text().splitlines():
        if "=" in line and line.split("=")[0].strip().lower() == "dt":
            return float(line.split("=")[1].split(";")[0].strip())
    raise ValueError(f"{mdp}: no dt found")


def _required_discard_ps(cfg: dict) -> float:
    """How much of each replica is non-stationary, in ps.

    Every bias schedule (`equilibrate_steps` + `ramp_steps`) is steered, not sampled
    at the declared setting. Persisting this with the campaign stops the collector
    from applying a generic default: the inversion ladder ramps for 30 ps at dt=1fs,
    so a 20 ps default would admit 10 ps of steered frames into a dataset documented
    as fixed-window.

    Explicit `discard_ps` in the config wins; otherwise it is derived from the longest
    schedule across the declared biases.
    """
    if cfg.get("discard_ps") is not None:
        return float(cfg["discard_ps"])
    dt = _mdp_dt_ps(Path(cfg["mdp"]))
    longest = 0
    for b in cfg.get("biases", []):
        base = {k: v for k, v in b.items() if k != "per_replica"}
        for key in ("equilibrate_steps", "ramp_steps"):
            vals = [base.get(key, 0)] + list((b.get("per_replica") or {}).get(key, []))
            longest_key = max(int(v) for v in vals if v is not None)
            base[key] = longest_key
        longest = max(longest, base["equilibrate_steps"] + base["ramp_steps"])
    # 10% headroom: the ramp ends at the target, but relaxation into the window is
    # not instantaneous.
    schedule_ps = longest * dt * 1.1
    # Floor: `_write_mdp` gives every replica fresh Maxwell-Boltzmann velocities
    # (gen_vel=yes, continuation=no), so there is a thermalisation transient even for
    # a bias that declares no schedule at all -- without this floor a TICA-only
    # campaign would compute 0 ps and keep the whole transient.
    return round(max(schedule_ps, float(cfg.get("min_discard_ps", 20.0))), 3)


def _resolve_per_replica(bias: dict, replica: int) -> dict:
    """Expand a bias's `per_replica:` block into concrete values for this replica.

    Umbrella windows need a different parameter per replica (one `chi_target` each),
    which the flat config cannot express:

        - type: local_inversion_umbrella
          force_constant: 2000.0
          per_replica:
            chi_target: [-0.71, -0.65, ..., 0.0]

    Each list under `per_replica` must have one entry per replica; it is indexed and
    merged over the base keys. Kept explicit rather than "any list value is a ladder"
    so a bias taking a genuine list parameter is not silently reinterpreted.
    """
    out = {k: v for k, v in bias.items() if k != "per_replica"}
    for key, values in (bias.get("per_replica") or {}).items():
        if not isinstance(values, (list, tuple)):
            raise ValueError(f"per_replica.{key} must be a list, got {type(values).__name__}")
        if replica >= len(values):
            raise ValueError(
                f"per_replica.{key} has {len(values)} entries but replica {replica} "
                f"was requested -- it must have one per replica"
            )
        out[key] = values[replica]
    return out


def _resolve_structure(cfg: dict, replica: int) -> str:
    """Per-replica starting structure, if the config supplies a list.

    Independent velocities alone leave every replica in the same basin; distinct
    starting conformations are what make the replicas sample different regions.
    """
    s = cfg["structure"]
    if isinstance(s, (list, tuple)):
        if replica >= len(s):
            raise ValueError(
                f"structure list has {len(s)} entries but replica {replica} was requested"
            )
        return str(s[replica])
    return str(s)


def _write_mdp(src: Path, dst: Path, replica: int, cfg: dict) -> None:
    """Copy the mdp, giving each replica its own initial velocities.

    Without this every replica starts from the same .gro with `gen_vel = no` and
    an unseeded deterministic integrator, so the twelve trajectories are the SAME
    trajectory. The pilot only diverged because GPU force accumulation is not
    bitwise reproducible and Lyapunov growth amplified that noise -- i.e. the
    independence was an accident of the hardware, and on a deterministic backend
    an N-replica campaign would silently yield N copies of one trajectory.

    Seeding velocities makes the independence explicit and reproducible. Costs a
    short re-equilibration, which the bias `equilibrate_steps` window and the
    collector's `--discard-ps` already cover.
    """
    seed0 = int(cfg.get("gen_seed_base", 20260803))
    overrides = {
        "gen_vel": "yes",
        "gen_temp": str(cfg.get("gen_temp", 298)),
        "gen_seed": str(seed0 + replica),
        # constraints must be re-applied to freshly generated velocities
        "continuation": "no",
    }
    seen = set()
    lines = []
    for line in src.read_text().splitlines():
        key = line.split("=")[0].strip().replace("-", "_").lower() if "=" in line else ""
        if key in overrides:
            lines.append(f"{key:<24}= {overrides[key]}   ; per-replica (cases.py)")
            seen.add(key)
        else:
            lines.append(line)
    trailing = [f"{k:<24}= {v}   ; per-replica (cases.py)"
                for k, v in overrides.items() if k not in seen]
    if trailing:
        lines += ["", "; --- independent-replica seeding, added by cases.py ---"] + trailing
    dst.write_text("\n".join(lines) + "\n")


def _write_multidir_scripts(out: Path, cfg: Dict[str, Any], n: int, backend: str) -> None:
    """One parent script per multidir group, plus a SLURM array over the groups.

    Replicas stay in their own `replica_NN/` dirs so `collect.py` is unaffected; only the
    launch topology changes.
    """
    from .launch import cpus_per_rank, group_ranges, multidir_group_script, submit_script

    per_job = int(cfg.get("replicas_per_job", n))
    groups = group_ranges(n, per_job)
    node_cpus = int(cfg.get("node_cpus", 288))
    # ntomp MUST equal --cpus-per-task, or SLURM and GROMACS disagree about the node budget
    ntomp = cpus_per_rank(max(len(g) for g in groups), node_cpus)

    for gi, members in enumerate(groups):
        script = out / f"run_group_{gi:03d}.sh"
        script.write_text(multidir_group_script(
            case_dirs=[f"replica_{r:02d}" for r in members],
            structure_for=[_resolve_structure(cfg, r) for r in members],
            topology=cfg["topology"],
            # NOT cfg["ntomp"]: that value is sized for the per-case topology (1 rank owning
            # the node) and would contradict --cpus-per-task here. Override with
            # `multidir_ntomp` if you really want to.
            ntomp=int(cfg.get("multidir_ntomp") or ntomp),
            n_gpus=int(cfg.get("gpus_per_node", 4)),
            repo=str(REPO),
            socket_dir=str(cfg.get("socket_dir", "/tmp")),
            campaign_name=cfg["name"],
            replicas=members,
            socket_timeout=float(cfg.get("socket_timeout_s", 600.0)),
            use_server=(backend == "python"),
            mps=bool(cfg.get("cuda_mps", False)),
        ))
        script.chmod(0o755)

    (out / "submit.slurm").write_text(submit_script(
        campaign_dir=out, groups=groups, job_name=cfg["name"],
        hours=float(cfg.get("wall_hours", 2.0)),
        n_gpus=int(cfg.get("gpus_per_node", 4)), node_cpus=node_cpus,
    ))
    print(f"  launch: multidir, {len(groups)} group(s) of up to {per_job} replicas "
          f"({'with' if backend == 'python' else 'no'} bias servers), "
          f"ntomp={ntomp} ({max(len(g) for g in groups)} ranks x {ntomp} = "
          f"{max(len(g) for g in groups) * ntomp}/{node_cpus} CPUs)")
    print(f"  submit: sbatch {out}/submit.slurm")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--config", type=Path, required=True)
    ap.add_argument("--output-dir", type=Path, default=None)
    args = ap.parse_args()

    cfg = yaml.safe_load(args.config.read_text())
    backend = str(cfg.get("bias_backend", "python")).lower()
    if backend not in ("python", "plumed"):
        raise SystemExit(f"bias_backend must be 'python' or 'plumed', got {backend!r}")
    # The plugin is only needed by the socket route; a native campaign never loads it.
    if backend == "python" and not PLUGIN_SO.exists():
        raise SystemExit(
            f"{PLUGIN_SO} missing -- run sampling/plugin/compile_plugin.sh first"
        )
    if backend == "plumed":
        ok, blockers = native_backend_supported(cfg)
        if not ok:
            raise SystemExit(
                f"bias_backend: plumed cannot express {blockers}; "
                f"native types are {sorted(NATIVE_BIAS_TYPES)}"
            )

    out = Path(args.output_dir or cfg["output_dir"])
    out.mkdir(parents=True, exist_ok=True)
    mapping = get_mapping(cfg["mapping"])

    n = int(cfg["n_replicas"])
    for replica in range(n):
        build_case(out / f"replica_{replica:02d}", replica, cfg)

    launch = str(cfg.get("launch", "per-case")).lower()
    if launch not in ("per-case", "multidir"):
        raise SystemExit(f"launch must be 'per-case' or 'multidir', got {launch!r}")
    if launch == "multidir":
        _write_multidir_scripts(out, cfg, n, backend)

    (out / "campaign.json").write_text(
        json.dumps(
            {
                "name": cfg["name"],
                "mapping": mapping.name,
                "n_beads": mapping.n_beads,
                "plumed_atoms": mapping.plumed_atom_selection(),
                "n_replicas": n,
                "biases": [b.get("type") for b in cfg["biases"]],
                # Recorded so a collected dataset can always be traced back to which bias
                # implementation produced it -- the two routes are equivalent but not
                # bit-identical (native PLUMED evaluates every step, the plugin caches over
                # RECOMPUTE_STRIDE).
                "bias_backend": backend,
                "required_discard_ps": _required_discard_ps(cfg),
                "temperature_note": "must match the atomistic reference (298 K for ala2)",
            },
            indent=2,
        )
    )
    print(f"wrote {n} cases under {out}")
    print(f"  mapping {mapping.name} ({mapping.n_beads} beads), ATOMS={mapping.plumed_atom_selection()}")
    print(f"  biases: {[b.get('type') for b in cfg['biases']]}")


if __name__ == "__main__":
    main()
