#!/usr/bin/env python3
"""Generate a CG-biased enhanced-sampling campaign from one YAML.

Writes, per replica: a PLUMED input, a bias-server config, and a run script that
starts the server, runs biased MD, then reruns forces WITHOUT the bias so the exported
labels are physical.

    python -m sampling.cases --config sampling/campaigns/ala2_bb6_pilot.yaml

The bias-free rerun is not optional. Biased dynamics saves f_AA + f_bias; force matching
must train on f_AA alone, or the model learns the sampler. See
KB DESIGN/MLCG_TEACHER_BIAS_SAMPLING.md ## Bias-Free Training Labels.
"""

from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path
from typing import Any, Dict

import yaml

from .mapping import get_mapping

REPO = Path(__file__).resolve().parent.parent
PLUGIN_SO = REPO / "sampling" / "plugin" / "CGBias.so"


PLUMED_TEMPLATE = """\
# Generated by sampling/cases.py -- do not edit by hand.
# replica {replica}   mapping {mapping}   {n_beads} beads
LOAD FILE={plugin_so}

WHOLEMOLECULES ENTITY0={atoms}

# All bias logic lives in the server; this action is transport only.
cgbias: CG_BIAS ATOMS={atoms} SOCKET={socket} RECOMPUTE_STRIDE={recompute_stride} TIMEOUT={socket_timeout}
BIASVALUE ARG=cgbias

# Monitoring CVs (not biased directly)
{cv_lines}
PRINT ARG={cv_names},cgbias FILE=colvar.dat STRIDE={print_stride}
"""


RUN_TEMPLATE = """\
#!/bin/bash
# Generated by sampling/cases.py -- do not edit by hand.
set -Eeuo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
cd "$HERE"

SOCKET="{socket}"
rm -f "$SOCKET"

# ---- 1. bias server (one per replica) --------------------------------------
source {repo}/env_setup/load_modules_2026.sh
source {repo}/../venv_cameocg_jupiter2026/bin/activate
export JAX_PLATFORMS=cpu          # teacher runs beside GROMACS on CPU
cd {repo}
python -m sampling.server --config "$HERE/server.yaml" --socket "$SOCKET" \\
    --log "$HERE/server_events.log" --io-timeout {socket_timeout} > "$HERE/server.log" 2>&1 &
SERVER_PID=$!
trap 'kill $SERVER_PID 2>/dev/null || true; rm -f "$SOCKET"' EXIT
cd "$HERE"

for _ in $(seq 1 120); do [ -S "$SOCKET" ] && break; sleep 1; done
[ -S "$SOCKET" ] || {{ echo "bias server never created $SOCKET" >&2; cat "$HERE/server.log" >&2; exit 1; }}

# ---- 2. biased production ---------------------------------------------------
module --force purge
module load Stages/2025
module load GCC/13.3.0 ParaStationMPI/5.11.0-1
module load GROMACS/2024.3-PLUMED-2.9.3

gmx grompp -f production.mdp -c {structure} -p {topology} -o biased.tpr -maxwarn 2
gmx mdrun -deffnm biased -plumed plumed.dat -ntmpi 1 -ntomp {ntomp}

# ---- 3. bias-free force rerun (MANDATORY for training labels) --------------
gmx mdrun -s biased.tpr -rerun biased.trr -deffnm unbiased_forces -ntmpi 1 -ntomp {ntomp}

echo "case {replica} complete: biased.trr + unbiased_forces.trr"
"""


def build_case(case_dir: Path, replica: int, cfg: Dict[str, Any]) -> None:
    case_dir.mkdir(parents=True, exist_ok=True)
    mapping = get_mapping(cfg["mapping"])
    atoms = mapping.plumed_atom_selection()
    socket = str(Path(cfg.get("socket_dir", "/tmp")) / f"cgbias_{cfg['name']}_r{replica}.sock")

    cv_lines, cv_names = [], []
    for cv_name in cfg.get("monitor_cvs", ["phi", "psi"]):
        cv = mapping.cvs[cv_name]
        idx = ",".join(str(i) for i in cv.atom_indices_1based(mapping))
        cv_lines.append(f"{cv_name}: TORSION ATOMS={idx}")
        cv_names.append(cv_name)

    (case_dir / "plumed.dat").write_text(
        PLUMED_TEMPLATE.format(
            replica=replica,
            mapping=mapping.name,
            n_beads=mapping.n_beads,
            plugin_so=PLUGIN_SO,
            atoms=atoms,
            socket=socket,
            cv_lines="\n".join(cv_lines),
            cv_names=",".join(cv_names),
            print_stride=int(cfg.get("print_stride", 500)),
            recompute_stride=int(cfg.get("recompute_stride", 1)),
            socket_timeout=float(cfg.get("socket_timeout_s", 600.0)),
        )
    )

    server_cfg = {
        "mapping": mapping.name,
        "report_every": int(cfg.get("report_every", 500)),
        "biases": [_resolve_per_replica(b, replica) for b in cfg["biases"]],
    }
    (case_dir / "server.yaml").write_text(yaml.safe_dump(server_cfg, sort_keys=False))

    run = case_dir / "run_case.sh"
    run.write_text(
        RUN_TEMPLATE.format(
            replica=replica,
            socket=socket,
            repo=REPO,
            structure=_resolve_structure(cfg, replica),
            topology=cfg["topology"],
            ntomp=int(cfg.get("ntomp", 8)),
            socket_timeout=float(cfg.get("socket_timeout_s", 600.0)),
        )
    )
    run.chmod(0o755)

    mdp_src = Path(cfg["mdp"])
    _write_mdp(mdp_src, case_dir / "production.mdp", replica, cfg)


def _mdp_dt_ps(mdp: Path) -> float:
    for line in mdp.read_text().splitlines():
        if "=" in line and line.split("=")[0].strip().lower() == "dt":
            return float(line.split("=")[1].split(";")[0].strip())
    raise ValueError(f"{mdp}: no dt found")


def _required_discard_ps(cfg: dict) -> float:
    """How much of each replica is non-stationary, in ps.

    Every bias schedule (`equilibrate_steps` + `ramp_steps`) is steered, not sampled
    at the declared setting. Persisting this with the campaign stops the collector
    from applying a generic default: the inversion ladder ramps for 30 ps at dt=1fs,
    so a 20 ps default would admit 10 ps of steered frames into a dataset documented
    as fixed-window.

    Explicit `discard_ps` in the config wins; otherwise it is derived from the longest
    schedule across the declared biases.
    """
    if cfg.get("discard_ps") is not None:
        return float(cfg["discard_ps"])
    dt = _mdp_dt_ps(Path(cfg["mdp"]))
    longest = 0
    for b in cfg.get("biases", []):
        base = {k: v for k, v in b.items() if k != "per_replica"}
        for key in ("equilibrate_steps", "ramp_steps"):
            vals = [base.get(key, 0)] + list((b.get("per_replica") or {}).get(key, []))
            longest_key = max(int(v) for v in vals if v is not None)
            base[key] = longest_key
        longest = max(longest, base["equilibrate_steps"] + base["ramp_steps"])
    # 10% headroom: the ramp ends at the target, but relaxation into the window is
    # not instantaneous.
    schedule_ps = longest * dt * 1.1
    # Floor: `_write_mdp` gives every replica fresh Maxwell-Boltzmann velocities
    # (gen_vel=yes, continuation=no), so there is a thermalisation transient even for
    # a bias that declares no schedule at all -- without this floor a TICA-only
    # campaign would compute 0 ps and keep the whole transient.
    return round(max(schedule_ps, float(cfg.get("min_discard_ps", 20.0))), 3)


def _resolve_per_replica(bias: dict, replica: int) -> dict:
    """Expand a bias's `per_replica:` block into concrete values for this replica.

    Umbrella windows need a different parameter per replica (one `chi_target` each),
    which the flat config cannot express:

        - type: local_inversion_umbrella
          force_constant: 2000.0
          per_replica:
            chi_target: [-0.71, -0.65, ..., 0.0]

    Each list under `per_replica` must have one entry per replica; it is indexed and
    merged over the base keys. Kept explicit rather than "any list value is a ladder"
    so a bias taking a genuine list parameter is not silently reinterpreted.
    """
    out = {k: v for k, v in bias.items() if k != "per_replica"}
    for key, values in (bias.get("per_replica") or {}).items():
        if not isinstance(values, (list, tuple)):
            raise ValueError(f"per_replica.{key} must be a list, got {type(values).__name__}")
        if replica >= len(values):
            raise ValueError(
                f"per_replica.{key} has {len(values)} entries but replica {replica} "
                f"was requested -- it must have one per replica"
            )
        out[key] = values[replica]
    return out


def _resolve_structure(cfg: dict, replica: int) -> str:
    """Per-replica starting structure, if the config supplies a list.

    Independent velocities alone leave every replica in the same basin; distinct
    starting conformations are what make the replicas sample different regions.
    """
    s = cfg["structure"]
    if isinstance(s, (list, tuple)):
        if replica >= len(s):
            raise ValueError(
                f"structure list has {len(s)} entries but replica {replica} was requested"
            )
        return str(s[replica])
    return str(s)


def _write_mdp(src: Path, dst: Path, replica: int, cfg: dict) -> None:
    """Copy the mdp, giving each replica its own initial velocities.

    Without this every replica starts from the same .gro with `gen_vel = no` and
    an unseeded deterministic integrator, so the twelve trajectories are the SAME
    trajectory. The pilot only diverged because GPU force accumulation is not
    bitwise reproducible and Lyapunov growth amplified that noise -- i.e. the
    independence was an accident of the hardware, and on a deterministic backend
    an N-replica campaign would silently yield N copies of one trajectory.

    Seeding velocities makes the independence explicit and reproducible. Costs a
    short re-equilibration, which the bias `equilibrate_steps` window and the
    collector's `--discard-ps` already cover.
    """
    seed0 = int(cfg.get("gen_seed_base", 20260803))
    overrides = {
        "gen_vel": "yes",
        "gen_temp": str(cfg.get("gen_temp", 298)),
        "gen_seed": str(seed0 + replica),
        # constraints must be re-applied to freshly generated velocities
        "continuation": "no",
    }
    seen = set()
    lines = []
    for line in src.read_text().splitlines():
        key = line.split("=")[0].strip().replace("-", "_").lower() if "=" in line else ""
        if key in overrides:
            lines.append(f"{key:<24}= {overrides[key]}   ; per-replica (cases.py)")
            seen.add(key)
        else:
            lines.append(line)
    trailing = [f"{k:<24}= {v}   ; per-replica (cases.py)"
                for k, v in overrides.items() if k not in seen]
    if trailing:
        lines += ["", "; --- independent-replica seeding, added by cases.py ---"] + trailing
    dst.write_text("\n".join(lines) + "\n")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--config", type=Path, required=True)
    ap.add_argument("--output-dir", type=Path, default=None)
    args = ap.parse_args()

    cfg = yaml.safe_load(args.config.read_text())
    if not PLUGIN_SO.exists():
        raise SystemExit(
            f"{PLUGIN_SO} missing -- run sampling/plugin/compile_plugin.sh first"
        )

    out = Path(args.output_dir or cfg["output_dir"])
    out.mkdir(parents=True, exist_ok=True)
    mapping = get_mapping(cfg["mapping"])

    n = int(cfg["n_replicas"])
    for replica in range(n):
        build_case(out / f"replica_{replica:02d}", replica, cfg)

    (out / "campaign.json").write_text(
        json.dumps(
            {
                "name": cfg["name"],
                "mapping": mapping.name,
                "n_beads": mapping.n_beads,
                "plumed_atoms": mapping.plumed_atom_selection(),
                "n_replicas": n,
                "biases": [b.get("type") for b in cfg["biases"]],
                "required_discard_ps": _required_discard_ps(cfg),
                "temperature_note": "must match the atomistic reference (298 K for ala2)",
            },
            indent=2,
        )
    )
    print(f"wrote {n} cases under {out}")
    print(f"  mapping {mapping.name} ({mapping.n_beads} beads), ATOMS={mapping.plumed_atom_selection()}")
    print(f"  biases: {[b.get('type') for b in cfg['biases']]}")


if __name__ == "__main__":
    main()
