#!/usr/bin/env python3
"""Write one NPZ dataset frame as a minimal LAMMPS atomic data file."""

import argparse
from pathlib import Path

import numpy as np


def _frame_value(array: np.ndarray, frame: int, n_frames: int) -> np.ndarray:
    if array.ndim > 1 and array.shape[0] == n_frames:
        return array[frame]
    return array


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dataset", required=True, help="Input NPZ containing R and resname or species.")
    parser.add_argument("--frame", type=int, default=0, help="Zero-based frame index (default: 0).")
    parser.add_argument("--output", required=True, help="Output LAMMPS data file.")
    parser.add_argument("--padding", type=float, default=20.0, help="Vacuum padding around coordinates in Angstrom.")
    args = parser.parse_args()

    if args.padding <= 0:
        parser.error("--padding must be positive")

    with np.load(args.dataset, allow_pickle=True) as data:
        R = np.asarray(data["R"])
        if R.ndim == 2:
            R = R[None, ...]
        if R.ndim != 3 or R.shape[-1] != 3:
            raise ValueError(f"R must have shape (frames, atoms, 3); got {R.shape}")
        if not 0 <= args.frame < R.shape[0]:
            raise IndexError(f"frame {args.frame} outside [0, {R.shape[0]})")

        pos = np.asarray(R[args.frame], dtype=float)
        if "mask" in data:
            mask = np.asarray(_frame_value(np.asarray(data["mask"]), args.frame, R.shape[0]), dtype=bool)
            pos = pos[mask]
        else:
            mask = np.ones(pos.shape[0], dtype=bool)

        if "resname" in data:
            resnames = np.asarray(_frame_value(np.asarray(data["resname"]), args.frame, R.shape[0]))[mask]
            names = [str(value) for value in resnames]
            unique_names = sorted(set(names))
            name_to_type = {name: idx + 1 for idx, name in enumerate(unique_names)}
            atom_types = np.asarray([name_to_type[name] for name in names], dtype=int)
        elif "species" in data:
            species = np.asarray(_frame_value(np.asarray(data["species"]), args.frame, R.shape[0]))[mask]
            atom_types = species.astype(int) + 1
        else:
            raise KeyError("dataset must contain resname or species")

    if pos.shape[0] == 0:
        raise ValueError("selected frame contains no unmasked atoms")
    n_types = int(atom_types.max())
    lower = pos.min(axis=0) - args.padding
    upper = pos.max(axis=0) + args.padding

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w") as handle:
        handle.write("LAMMPS data file generated by md_setup/lmp_input_gen.py\n\n")
        handle.write(f"{pos.shape[0]} atoms\n")
        handle.write(f"{n_types} atom types\n\n")
        for axis, lo, hi in zip("xyz", lower, upper):
            handle.write(f"{lo:.8f} {hi:.8f} {axis}lo {axis}hi\n")
        handle.write("\nAtoms\n\n")
        for atom_id, (atom_type, xyz) in enumerate(zip(atom_types, pos), start=1):
            handle.write(
                f"{atom_id} {int(atom_type)} {xyz[0]:.8f} {xyz[1]:.8f} {xyz[2]:.8f}\n"
            )

    print(f"Wrote {pos.shape[0]} atoms and {n_types} types to {output}")


if __name__ == "__main__":
    main()
